### ISSUE TITLE
Detect max.poll.interval.ms expiration

### ISSUE THREAD

**Issue by diegobarbosa** [confluentinc/confluent-kafka-dotnet#1157] opened 2020-01-07 20:36 UTC
Description
===========

Some time my consumer throws ConsumeException:

> Confluent.Kafka.ConsumeException: Local: Maximum application poll interval (max.poll.interval.ms) exceeded

 >  at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
   at Confluent.Kafka.Consumer`2.Consume(TimeSpan timeout)

The log informs:

> Application maximum poll interval (300000ms) exceeded by 2134298747ms (adjust max.poll.interval.ms for long-running message processing): leaving group 

and the consumer stops receiving new messages (consume() returns null).

Is there are a way of detect when max.poll.interval.ms occours?

Is there another way besides try to check the exception message?

I was searching and found [931](https://github.com/confluentinc/confluent-kafka-dotnet/issues/931).

[2316](https://github.com/edenhill/librdkafka/pull/2316) has been released?

Lib Version: 1.2.2.0

**Comment by AndyPook** [comment] 2020-01-09 18:52
Hi,

This is usually caused because Consume is not being called often enough (there can be some house-keeping interaction with the broker at this point).
Typically there's a consume/handle loop (ie consume to get a message; process the message; repeat). If your handle method/processing takes longer than the interval then you will see this exception.

I have seen this where a circuit-breaker was added so that the consumer could be "paused". but that meant that the consumer wasn't able to do its house-keeping and the interval expires and the exception is thrown.
More simply, it can be seen if you leave the debugger on a break point for too long.

Usually, when the "loop" starts again, the underlying client is smart enough to restart the connection. Consume()==null can happen legitimately. Publish another message and you should see the consumer resume.

A massively simplified message loop...
```csharp
while(!cancellationToken.IsCancellationRequested)
{
  var msg = consumer.Consume( 100ms or cancellationToken );
  if (msg == null || msg.IsPartitionEOF)
    continue;

  Handle(msg);
}
```
If `Handle` takes longer than 300000ms (5 minutes) then you have other problems !
(note: if you pass a cancellationToken, internally it's just a loop of `Consume(100)` waiting for the ct to be cancelled. Depending on what you're trying to do, you take you choice...)

I hope this makes some sense?
Happy to help further if you can share some more on what code pattern you are using.

**Comment by alfhv** [comment] 2020-04-25 09:54
I'm having similar situation as you describe in previous post. I have a Handle(mg) that takes too long to process the message, and this is normal, sometime the process is too long, about 20 or 30min.
I have AutoCimmit to false as I want to commit only if process is succesful, if not I retry the msg later.
When Handle finish and I try to Commit then I'm having exception because the consumer was disconected due to timeouts, I think.
I already increase maxpoolIntervalMs and SessionTimeoutMs to 30min but from time to time I reach this limit and consumer get disconected.
My question is: how bg can I set timeouts to allow a very long processing time before commit and if this is safe for the app to have a big timeout values.

**Comment by Rymix** [comment] 2020-04-25 16:25
How you Consume your messages ? What parameters do you give

**Comment by alfhv** [comment] 2020-04-25 18:05
I have very simple loop as 

```
consumerConfig.AutoOffsetReset = AutoOffsetReset.Earliest;
consumerConfig.EnableAutoCommit = false;
consumerConfig.SessionTimeoutMs = 1000 * 60 * 30; //30min
consumerConfig..MaxPollIntervalMs = 1000 * 60 * 30;  //30min

ConsumerBuilder = new ConsumerBuilder<TKey, TValue>(consumerConfig)
uing (var consumer = ConsumerBuilder.Build())
{  
  while(!cancellationToken.IsCancellationRequested)
  {
    var msg = consumer.Consume( 100ms or cancellationToken );
    if (msg == null || msg.IsPartitionEOF || cancellationToken.IsCancellationRequested)
      continue;

    Handle(msg); // could takes more than 30min
    consumer.Commit(msg);
  }  
}
```

**Comment by alfhv** [comment] 2020-04-27 08:56
Now testing with big values in SessionTimeoutMs and MaxPollIntervalMs (30min I have a very annoying situation.
Seems that these values "delays" the consumer to start consumming only after 30min !!
Consumer not even appears as connected in kafka-consumer-groups.sh console in the meantime.
are sessiontimeout and maxpoolinterval related with consumer start consumming ?
How to reproduce:

- Create simple consumer with config:
consumerConfig.SessionTimeoutMs = 1000 * 60 * 30; //30min
consumerConfig..MaxPollIntervalMs = 1000 * 60 * 30;  //30min
- Let consumer run and be registered as a kown consumergroupID.
- disconnect the consumer, check consumergroupID is still registered but without actif clients.
- remove config values consumerConfig.SessionTimeoutMs and consumerConfig..MaxPollIntervalMs
- restart consumer.

I have tried with a very simple console app, and after resetting timeout to default consumer stay without consume messages just after previous timeout values.

**Comment by AndyPook** [comment] 2020-04-27 11:53
I haven't been using Kafka for a few months, but still get notifications, so thought I'd a my 2p (british)

The "problem" is that the client needs to interact with the broker regularly. This is how the broker decides that the client is "alive", maintains consumer groups etc. 

If your handler really takes that long to process a message (!), I would suggest a different strategy.
read a message; dispatch the Handle to a different thread/Task; allow the loop to continue (using much short poll interval).
If Handle is executing. then ignore the new message and continue the loop so that it will Consume (ie poll). When Handle completes, then you can handle the new message. (you will need threadsafe sync between the loop and Handle. In this case a simple 1 or 0 int with Interlocked.exchange would be fine.)

This may seem a little nasty and inefficient. But, remember that the Consume is working off a local buffer. So the only cost is some memory marshaling. 

The idea is to allow polling to occur regularly while at the same time, processing a message.

It may also be possible to split whatever Handle is doing into several steps. Each step is a separate event/consumer/service. So you get a sequence of "events". This might also allow easy parallelization of some of the processing with easy scale out by increasing the consumers for that step.
Obviously, conservation of complexity applies, as you will now need to deal with fan out/in.
Also, obviously, I have no idea what Handle is doing, so this might be completely inappropriate :)

**Comment by alfhv** [comment] 2020-04-27 12:15
I understand big timeout could cause issues, that's why my previous question:

> My question is: how big can I set timeouts to allow a very long processing time before commit and if this is safe for the app to have a big timeout values.

On the other hand, I'm restarting the consumer and I'm expecting that connections be reset and restablished when consumer start, and I dont understand why at this moment the sessionTimeout delay the consumption of messages.

I could optimize and break in parallel the process in my Handle but in all cases I will have some minutes of processing time, so I need to increase timeouts and I dont want this same timeout delay the consumer to start processing messages when restarting.

SessionTimeoutMs and MaxPollIntervalMs seems to be aplied at consumergroup level and not at session lifetime... is that the desired behavior ?

**Comment by edenhill** [comment] 2020-04-27 12:24
SessionTimeoutMs is the lively-ness timeout of a consumer client, it should be set low (or preferably left at its default value).
If your consumer crashes and is restarted the SessionTimeoutMs decides how long it will take the group to rebalance, that's why you are seeing such long join times on restart.


MaxPollIntervalMs is the lively-ness timeout of the application, it must check in (poll for a message) at least this often or it will be deemed malfunctional and the consumer will leave the group (until the application starts polling again).
The MaxPollIntervalMs is also the maximum time allowed for an application to process a single message, thought of it is in more data centric terms is it defines how long this consumer instance (in a consumer group) owns a message.

**Comment by alfhv** [comment] 2020-04-27 12:36
so, as I need to deal with long processing time, and avoid reach timeouts that will disconnect my consumer, there is a way to keep my consumer interacting with broker (to keep connection alive) whitout polling new messages ?
I can't process next message before finish current, I can't commit before finish with message.

the Pause and Resume could do the work ??Pausing consumer keep connection alive ?

ex:

```
while(!cancellationToken.IsCancellationRequested)
{
  var msg = consumer.Consume( cancellationToken );
  if (msg == null || msg.IsPartitionEOF || cancellationToken.IsCancellationRequested)
    continue;

  consumer.Pause(new[] { msg.TopicPartition });
  Handle(msg.Value); // long process
  consumer.Resume(new[] { msg.TopicPartition });

  consumer.Commit(msg)
}
```

**Comment by edenhill** [comment] 2020-04-27 12:38
Yes, that is a viable alternative.
Since Pause() will purge the pre-fetch queue you'll probably want to minimize the size of that queue by setting QueuedMinMessages and QueudMaxMessagesKbytes to 1.

**Comment by alfhv** [comment] 2020-04-27 16:27
well it din't work...
I got: "Broker: unknown member" after Resuming Consumer...
QueuedMinMessages and QueudMaxMessagesKbytes to 1.
all timeouts values by default.

consumer was reported disconnected on kafka-console about 5min after start and before Handle finish.

Seems Pause() did't bypass timeouts ??

any idea ?

**Comment by alfhv** [comment] 2020-04-27 18:32
trying to resume lost connection i do this:

```
var a = consumer.Assignment; // save current assignment
Handler(msg); // start long process

if (!consumer.Assignment.Any())
{
  // connection lost (maybe another way to check it ?
  consumer.Assign(a); // reassign 
}
consumer.Commit(msg); 
```
The offset was correctly moved on broker, but when loop try to Consume() msg again then I got consumer disconnected error.
Assign() dont resume connection, neither consumer.Consume()...
any way to force consumer to reconnect ??

**Comment by edenhill** [comment] 2020-04-28 07:06
Sorry, I was not very clear, you must still call Consume() at least every max.poll.interval.ms, even if you've done Pause() (Pause only keeps you from getting new messages from Consume()).

But you should really set max.poll.interval.ms to the maximum processing time + some extra time, and as soon as you've processed a message you should (optionally commit) and call Consume() again before max.poll.. is exceeded.

**Comment by edenhill** [comment] 2020-04-28 07:07
You should not call Assign() outside of OnPartitionsAssigned/Revoked

**Comment by anchitj** [comment] 2024-06-04 12:25
Closing, as all the queries are answered above.

**Closed by anchitj** 2024-06-04 12:25 UTC
