### ISSUE TITLE
AWS Lambda .NET Core 2.0

### ISSUE THREAD

**Issue by ematuschek** [confluentinc/confluent-kafka-dotnet#466] opened 2018-03-19 15:32 UTC
Description
===========
I am currently using verison 0.11.3 from the Microsoft Nuget Package manager.

I'm attempting to create just a simple lambda in a .NET Core 2.0 project that can use the confluent-kafka-dotnet library to talk to another AWS server that is running kafka. I'm able to run the function locally with no issue, but when I deploy to AWS I get "Failed to load the librdkafka native library.: DllNotFoundException". I believe I got around this by adding "Library.Load("librdkafka/x64/librdkafka.dll");" at the beginning of the function, but then I got another of the same error only this time referencing the libdl library. This library is not in the solution as librdkafka was, so I'm not sure how to reference it using a Library.Load...and whether there will be more libraries that have this same issue?

How to reproduce
================
Deploy a simple AWS Lambda using the Confluent.Kafka 0.11.3 nuget package.

**Comment by mhowlett** [comment] 2018-07-26 20:18
#572 is a duplicate of this, I responded there (sorry for not responding here).

**Closed by mhowlett** 2018-07-26 20:18 UTC
Labels: duplicate
