### ISSUE TITLE
specify partition for one consumer in a group can not rebalance the others

### ISSUE THREAD

**Issue by wangjia184** [confluentinc/confluent-kafka-dotnet#1106] opened 2019-11-06 05:46 UTC
I have a topic with 150 partitions [0 - 149]
And I have three consumers joinning the same group. 

By default, each consumer is assigned with their own ranges.
* Consumer A : [0-49]
* Consumer B : [50-99]
* Consumer C : [100-149]

I want consumer B only consumes a specific partition. Hence within its `SetPartitionsRevokedHandler`,  only a specific one is returned.
```csharp
IEnumerable<TopicPartitionOffset> OnPartitionsAssigned(IConsumer<MessageKey, byte[]> consumer, List<TopicPartition> partitions)
 {
            return new TopicPartitionOffset[]
            {
                new TopicPartitionOffset(  new TopicPartition(_topic, 0), Offset.Unset),
            };
}
```

I expect consumer A and C would be assigned with partition [1 - 149]
I tested but it does not work in that way.   Consumer A & C are not rebalanced and they are still assigned with 50 partitions each.
* Consumer A : [0-49]
* Consumer C : [100-149]

Is this a bug of client?

Confluent.Kafka nuget version : 1.2.1
- Apache Kafka version : 0.10
- Client configuration :  EnableAutoCommit : false; AutoOffsetReset : Earliest

**Comment by mhowlett** [comment] 2019-11-06 23:41
this is operating as intended - the partitions you assign a client to read from are independent of the assignment given to you by the consumer group. the main use case (which is uncommon) of reading from a different set of partitions than that assigned is adding an additional 'control' partition to the set assigned to you by the CG. note that the java client doesn't let you specify the two independently.

you could achieve what you want with a custom partition assignment strategy, but that's currently not supported by the non-java clients.

finally, this request is unusual - feel free to give some more color so we can understand the reasoning behind the design.

**Comment by wangjia184** [comment] 2019-11-07 06:28
Thanks @mhowlett 
Our producer sends business data to Kafka.  For business reason, the order of the message is important. Hence the producer sends messages to specific partition.
e.g. Same client's messages are put into the same partition.

As a result,  the number of messages are not distributed well.  Some partition's size is 10x-100x of others.  Hence we want to use a dedicate consumer handling that particular partition.

Manual assignment would work in this case but hard to manage (especially considering one consumer is down)

* When dedicated consumer watchs on a specific partition;  Other consumers consume other partitions.
* When dedicated consumer is down,  other consumers consume all partitions.

**Comment by ChadJessup** [comment] 2019-11-27 05:32
> you could achieve what you want with a custom partition assignment strategy, but that's currently not supported by the non-java clients

I was just looking into whether or not we can use custom ConsumerPartitionAssignors, sounds like we can't?

Is this something that could be added to the C# library? Or, is there something more fundamentally different with the Java client that allows this? Depending on the answer/complexity, I'd be willing to take a stab at the changes, if needed.

**Comment by mhowlett** [comment] 2020-05-21 15:58
custom partition assignors should be fairly straightforward to add. for a long time. the blocker in adding them was working out what the api should look like, but post 1.0, that is now clear. we're likely to add this feature in the near future. closing as we're tracking this internally.

**Closed by mhowlett** 2020-05-21 15:58 UTC
Labels: question

**Comment by LGouellec** [comment] 2020-05-24 08:31
+1 for custom partition assignors feature, I need that for kafka stream .net implementation. Image you have a joiner processor between KStream(topic1) and one KTable(topic2). Your stream application is scalable, so you must have the same subscription partition in one instance of your application. Without custom partition assignors, it's very complicated to that, or maybe assign partition manually but more complicated.

**Comment by ChadJessup** [comment] 2020-05-24 20:05
> +1 for custom partition assignors feature, I need that for kafka stream .net implementation. Image you have a joiner processor between KStream(topic1) and one KTable(topic2). Your stream application is scalable, so you must have the same subscription partition in one instance of your application. Without custom partition assignors, it's very complicated to that, or maybe assign partition manually but more complicated.

@LGouellec - I've had a PR open for a few months at https://github.com/confluentinc/confluent-kafka-dotnet/pull/1133 with this.

If you're blocked, that might help you out until some official API comes into the picture.

**Comment by LGouellec** [comment] 2020-05-26 08:44
> > +1 for custom partition assignors feature, I need that for kafka stream .net implementation. Image you have a joiner processor between KStream(topic1) and one KTable(topic2). Your stream application is scalable, so you must have the same subscription partition in one instance of your application. Without custom partition assignors, it's very complicated to that, or maybe assign partition manually but more complicated.
> 
> @LGouellec - I've had a PR open for a few months at #1133 with this.
> 
> If you're blocked, that might help you out until some official API comes into the picture.

I can't see where I can set my custom partition assignor in your PR. 
I see your SetPartitioner(...) in ProducerBuilder, but my need is setting : Custom Partition Assignor (like JAVA Api) because with .net library, you just have both choice for partition assignor strategy (range ou roundrobin)

**Comment by ChadJessup** [comment] 2020-07-24 04:54
> > > +1 for custom partition assignors feature, I need that for kafka stream .net implementation. Image you have a joiner processor between KStream(topic1) and one KTable(topic2). Your stream application is scalable, so you must have the same subscription partition in one instance of your application. Without custom partition assignors, it's very complicated to that, or maybe assign partition manually but more complicated.
> > 
> > 
> > @LGouellec - I've had a PR open for a few months at #1133 with this.
> > If you're blocked, that might help you out until some official API comes into the picture.
> 
> @ChadJessup I can't see where I can set my custom partition assignor in your PR.
> I see your SetPartitioner(...) in ProducerBuilder, but my need is setting : Custom Partition Assignor (like JAVA Api) because with .net library, you just have both choice for partition assignor strategy (range ou roundrobin)

@LGouellec - you're right, sorry - I got confused on partitioners and assignors. I'm taking a look at adding assignors here real soon as a PR, but it'll probably wait on feedback on whatever happens with #1297
