### ISSUE TITLE
Unsubscribe does not trigger immediate rebalance

### ISSUE THREAD

**Issue by comdw** [confluentinc/confluent-kafka-dotnet#374] opened 2017-11-21 15:57 UTC
I'm testing out consumer groups and have several consumer instances with the same group id that have called Subscribe() for the same topic.

When I start a new consumer, a rebalance on existing consumers is triggered and all works as expected.

However when I (cleanly) stop consuming on one of the consumers, rebalancing is not triggered until the session timeout (30 seconds I think).  I.e. the same as if I just forcefully/uncleanly quit that consumer.

By cleanly stopping a consumer I mean calling Unsubscribe() followed by Dispose().  I've also tried adding a call to Unassign() before Unsubscribe() but this didn't change anything.

Is this a bug or am I doing something wrong?  I was going by the [confluent documentation](https://docs.confluent.io/current/clients/consumer.html) which states 

> For normal shutdowns, however, the consumer sends an explicit request to the coordinator to leave the group which triggers an immediate rebalance

... though I guess that might only apply to the Java client?

 - [X] Confluent.Kafka nuget version: 0.11.2
 - [X] Apache Kafka version: 0.11.0.1

**Comment by edenhill** [comment] 2017-11-21 16:03
You can troubleshoot this issue by enabling `debug` `cgrp` on the consumers, look for when the Heartbeat for the remaining consumers fail and the rebalance start to kick in. It should be shortly followed by a rebalance (OnPartitionsRevoked in .NET) and a LeaveGroupRequest.

**Comment by comdw** [comment] 2017-11-21 16:19
OK, so my consumer leaves at 16:09:50.  The remaining consumer gets normal heartbeat logs after this, e.g.

```
16:09:51 Debug | rdkafka#consumer-1 | HEARTBEAT | [thrd:main]: kafkadev03:9092/3: Heartbeat for group "group1" generation id 76
16:09:53 Debug | rdkafka#consumer-1 | HEARTBEAT | [thrd:main]: kafkadev03:9092/3: Heartbeat for group "group1" generation id 76
16:09:55 Debug | rdkafka#consumer-1 | HEARTBEAT | [thrd:main]: kafkadev03:9092/3: Heartbeat for group "group1" generation id 76
16:09:56 Debug | rdkafka#consumer-1 | HEARTBEAT | [thrd:main]: kafkadev03:9092/3: Heartbeat for group "group1" generation id 76
...etc...
```

This continues until about 30 seconds (the session timeout) later:

```
16:10:20 Debug | rdkafka#consumer-1 | HEARTBEAT | [thrd:main]: kafkadev03:9092/3: Heartbeat for group "group1" generation id 76
16:10:21 Debug | rdkafka#consumer-1 | HEARTBEAT | [thrd:main]: Group "group1" heartbeat error response in state up (join state started, 2 partition(s) assigned): Broker: Group rebalance in progress
16:10:21 Debug | rdkafka#consumer-1 | CGRPJOINSTATE | [thrd:main]: Group "group1" changed join state started -> init (v9, state up)
16:10:21 Debug | rdkafka#consumer-1 | ASSIGN | [thrd:main]: Group "group1": delegating revoke of 2 partition(s) to application rebalance callback on queue rd_kafka_cgrp_new: Broker: Group rebalance in progress
```

I could try and attach a complete set of logs if that would help...

**Comment by edenhill** [comment] 2017-11-21 16:21
That sort of indicates that the leaving consumer did not actually send a LeaveGroup, but is timed out instead.

Try `debug` `cgrp,protocol` on the leaving consumer, look for LeaveGroup

**Comment by comdw** [comment] 2017-11-21 16:44
Attached the log from the point I'm calling unsubscribe etc.  No mention of LeaveGroup, but then there isn't in the C# .NET client code either - it calls LibRdKafka.unsubscribe for Unsubscribe() and LibRdKafka.consumer_close for Dispose()

[leavingConsumerDebugLog.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/1492182/leavingConsumerDebugLog.txt)

**Comment by edenhill** [comment] 2017-11-21 16:48
Can you share your code that calls Unsubscribe()?

Also; you don't have to explicitly call Unsubscribe, closing the consumer is sufficient.

**Comment by comdw** [comment] 2017-11-21 17:15
I tried just disposing the consumer without calling unsubscribe first and it does behave differently (another log attached).  This time "leave group=yes".  But the behaviour on the remaining consumer didn't change - the revoke/rebalance appears to be happening only on the closing consumer.

[leavingConsumerDebugLog2.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/1492295/leavingConsumerDebugLog2.txt)

**Comment by edenhill** [comment] 2017-11-21 17:17
```
21/11/2017 17:09:13 Debug | rdkafka#consumer-1 | SEND | [thrd:kafkadev03:9092/3]: kafkadev03:9092/3: Sent LeaveGroupRequest (v0, 75 bytes @ 0, CorrId 28)
21/11/2017 17:09:13 Debug | rdkafka#consumer-1 | RECV | [thrd:kafkadev03:9092/3]: kafkadev03:9092/3: Received LeaveGroupResponse (v0, 2 bytes, CorrId 28, rtt 0.00ms)
```

The dispose-only triggered a LeaveGroup request, did you see anything interesting in the other consumer debug logs at this time? (Heartbeat failure)

**Comment by comdw** [comment] 2017-11-21 17:26
My apologies - it did indeed immediately trigger the rebalance on the other consumer!

Shouldn't the Unsubscribe call by itself trigger this rebalance though?  Not only that, but in my case something is happening to stop the leave group occurring when I Dispose.

**Comment by edenhill** [comment] 2017-11-21 17:30
Yes, Unsubscribe() will trigger a LeaveGroup when OnPartitionsRevoked returns (or specifically, when Unassign() is called from that delegate).


>  it did indeed immediately trigger the rebalance on the other consumer!
Seems contradictory to:
> Not only that, but in my case something is happening to stop the leave group occurring when I Dispose.

Can you elaborate?

**Comment by comdw** [comment] 2017-11-21 17:34
Sorry, I meant that in the case where I call Unsubscribe first, something happens to stop the leave group occurring when I then Dispose (so no immediate rebalance on the other consumer).  If I only call Dispose, then the leave group happens and the rebalance also happens immediately on the other consumer.

My OnPartitionsRevoked handler is calling Unassign().

**Comment by edenhill** [comment] 2017-11-21 17:40
Can you share your code that calls Unsubscribe, and the OnPartitions* delegates, I want to understand how you are using the APIs

**Comment by comdw** [comment] 2017-11-22 10:01
After a bit more debugging, I can say that no OnPartitionsRevoked is fired if I simply call Unsubscribe() - the logs say `delegating revoke of 2 partition(s) to application rebalance callback on queue rd_kafka_consumer_close: unsubscribe`.

Once I call Dispose() then I get the OnPartitionsRevoked event, which I respond to with Unassign().  This bit behaves differently depending on whether I called Unsubscribe() or not (as described previously).

I'll try and boil this down to the simplest console app possible and share when I have more time.

**Comment by edenhill** [comment] 2017-11-22 10:11
@mhowlett Can you look into why the rebalance_cb is not invoking OnPartitionsRevoked when Unsubscribe() is called?

**Comment by comdw** [comment] 2017-11-22 15:13
Now attached simplest console app that exhibits the problem.  Nothing special going on here.  You need to start two instances and use a topic with more than one partition.  Once things are up and running, press Ctrl-C on one instance to trigger the unsubscribe, followed by another keypress to dispose (no immediate rebalance).

Then run the whole thing again with the Unsubscribe call commented out (rebalances immediately).

[MultiConsumer.cs.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/1496447/MultiConsumer.cs.txt)

**Comment by mhowlett** [comment] 2017-11-22 17:31
I modified the above attached program to take a count value as an extra argument. I ran one instance with a very large value (so it wouldn't exit) and the other instance with smaller value and waited for it to exit. I see the `OnPartitionsRevoked` method is called immediately as expected on the instance that exits (note that `consumer.Unsubscribe` is called). I'm working on OSX. So if I understand correctly, in my related test the problem is not reproduced?

Could this be something to do with how librdkafka handles SIGINT? Could it be Windows specific? 

I think this is unlikely a problem with the dotnet client, as the calls through to librdkafka are straightforward.

Thanks for your detailed investigation @comdw, I'll leave this open and investigate more later (will run your program exactly as instructed on Windows). Also feel free to replicate my above test that avoids Ctrl-C and see what result you get.

**Comment by edenhill** [comment] 2017-11-22 19:50
librdkafka ignores all signals.

**Comment by comdw** [comment] 2017-11-23 09:05
Tried that modification and get the same result (no waiting for keypresses, the exiting consumer calls Unsubscribe before the implied Dispose at the end of the using block).

Is this part of the log not relevant to what is going on:

unsubscribe from current subscription of 1 topics (**leave group=no**,

vs when not calling unsubscribe first:

unsubscribe from current subscription of 1 topics (**leave group=yes**,

**Comment by comdw** [comment] 2017-12-15 13:44
@mhowlett - any progress on your investigation?  I'm still seeing this in latest release of the nuget package..

**Comment by comdw** [comment] 2018-01-10 09:20
Having been looking at this issue again and re-read the discussion above I realise I may not have explained properly what I perceive the issue to be:

Two consumers in the same group - Consumer A and Consumer B.
When Consumer A unsubscribes, I agree *its* partitions are immediately revoked, but I'm expecting **Consumer B** to immediately rebalance (revoke/assign) to pick up the partitions that are now not being consumed - surely its a rebalance event across the whole group?  Instead this happens 30 seconds later (session.timeout.ms I guess).

Maybe this is not the intended behaviour at all, but I'm sure I did get immediate rebalance when I omitted the Unsubscribe and just Disposed Consumer A.  I can't get this to happen at all now (on 0.11.3).

**Comment by edenhill** [comment] 2018-01-10 09:38
> I can't get this to happen at all now (on 0.11.3).

You can't get immediate rebalance to work at all? Or the delayed?

**Comment by comdw** [comment] 2018-01-10 10:33
I can't get immediate rebalance to happen on Consumer B when Consumer A unsubscribes, it happens after the delay session.timeout.ms.

Things do happen immediately locally on Consumer A when it unsubscribes.

**Comment by mhowlett** [comment] 2018-08-09 23:29
closing as this was resolved in the above mentioned commit, which has been released. please re-open if problem persists.

**Closed by mhowlett** 2018-08-09 23:29 UTC
