### ISSUE TITLE
Auto Offset Commit | add offset_store() support

### ISSUE THREAD

**Issue by cgosiak** [confluentinc/confluent-kafka-dotnet#31] opened 2017-02-01 18:22 UTC
I am not sure if this is a bug; but figured that it was not expected behavior. I am running an advanced consumer with the configuration:
```
new Dictionary<string, object>
            {
                {"group.id", _consumerGroup},
                {"enable.auto.commit", true},
                {"auto.commit.interval.ms", 5000},
                {"statistics.interval.ms", 60000},
                {"bootstrap.servers", brokerList},
                {
                    "default.topic.config", new Dictionary<string, object>()
                    {
                        {"auto.offset.reset", "largest"}
                    }
                }
            };
```
---
## Scenario 1)
- Advanced Producer Writing to Topic/Advanced Consumer Consuming
  - Offsets are committed every 5 seconds; as long as a new message comes in.
  - This is the expected behavior.

## Scenario 2)
- Advanced Producer is Turned Off/Topic Has Unconsumed Messages/Then Consumer is Turned On
  - Offsets are not committed until every message is received.
  - I do not believe this is the expected behavior.
---
I believe that offsets should be auto committed with the interval; regardless of the state of the producer.

**Comment by edenhill** [comment] 2017-02-01 18:42
Yes, your assumption is correct.

To clarify scenario 2:
your consumer starts reading from a previously committed offset, reads at least 1 message to catch up to the partition end, but even after 5000ms it hasn't committed that final offset?

**Comment by cgosiak** [comment] 2017-02-01 19:04
I have a topic and a consumer that has consumed all of the messages (the consumer is caught up)

I then close the consumer and produce some messages to the topic.  The consumer group is now behind.

I then open the consumer; it starts from where it last ended. However, none of the offsets are committed until each and every message from the topic is read. The commit happens after every message is received by the consumer.

**Comment by edenhill** [comment] 2017-02-01 19:07
And it takes longer than 5s for the consumer to catch up to the last message?

**Comment by cgosiak** [comment] 2017-02-01 19:13
Yes; to get through it takes upwards of a minute.

**Comment by edenhill** [comment] 2017-02-01 19:14
Is that due to message processing in your application or network/IO speed?

**Comment by cgosiak** [comment] 2017-02-01 19:15
The message processing in my application; I am just doing some testing when I noticed it. I could send a code snippet if that would help?

**Comment by cgosiak** [comment] 2017-02-01 19:19
I am running a modified version of the "Run_Poll" test case:
```
public static void Run_Poll(string brokerList, List<string> topics)
        {
            using (
                var consumer = new Consumer<Null, string>(constructConfig(brokerList, true), null,
                    new StringDeserializer(Encoding.UTF8)))
            {
                // Note: All event handlers are called on the main thread.

                consumer.OnMessage += (_, msg)=>
                {
                    Console.WriteLine($"Topic: {msg.Topic} Partition: {msg.Partition} Offset: {msg.Offset} {msg.Value}");
                   // running an arbitrarily long running piece of code; to make sure it takes longer than the offset.commit.interval to process message
                    var unhappy = true;
                    var random = new Random(DateTime.Now.Millisecond);
                    while (unhappy)
                    {
                        if (random.Next(100000000) == 46)
                        {
                            unhappy = false;
                        }
                    }
                };
                        

                consumer.OnPartitionEOF += (_, end)
                    =>
                        Console.WriteLine(
                            $"Reached end of topic {end.Topic} partition {end.Partition}, next message will be at offset {end.Offset}");

                consumer.OnError += (_, error)
                    => Console.WriteLine($"Error: {error}");

                consumer.OnOffsetCommit += (_, commit) =>
                {
                    Console.WriteLine($"[{string.Join(", ", commit.Offsets)}]");

                    if (commit.Error)
                    {
                        Console.WriteLine($"Failed to commit offsets: {commit.Error}");
                    }
                    Console.WriteLine($"Successfully committed offsets: [{string.Join(", ", commit.Offsets)}]");
                };

                consumer.OnPartitionsAssigned += (_, partitions) =>
                {
                    Console.WriteLine(
                        $"Assigned partitions: [{string.Join(", ", partitions)}], member id: {consumer.MemberId}");
                    consumer.Assign(partitions.Select(p => new TopicPartitionOffset(p, Offset.Invalid)));
                };

                consumer.OnPartitionsRevoked += (_, partitions) =>
                {
                    Console.WriteLine($"Revoked partitions: [{string.Join(", ", partitions)}]");
                    consumer.Unassign();
                };

                consumer.OnStatistics += (_, json)
                    => Console.WriteLine($"Statistics: {json}");

                consumer.Subscribe(topics);

                Console.WriteLine($"Subscribed to: [{string.Join(", ", consumer.Subscription)}]");

                var cancelled = false;
                Console.CancelKeyPress += (_, e) =>
                {
                    e.Cancel = true; // prevent the process from terminating.
                    cancelled = true;
                };

                Console.WriteLine("Ctrl-C to exit.");
                while (!cancelled)
                {
                    consumer.Poll(TimeSpan.FromMilliseconds(100));
                }
            }
        }
```

**Comment by edenhill** [comment] 2017-02-01 19:28
I have a theory:
 * the kafka consumer client prefetches messages from the broker and stores in local queues so that there are always messages available for the application to consume (e.g., no silly broker round-trip to get new ones), that's all taken care of in the background.
 * the default queue size is the intersection of queued.min.messages (def 100K) and queued.max.messages.kbytes (def 1GB)
 * fetched messages and callbacks are enqueued on the same internal queue for the application to handle (this queue is served by a .net background thread that calls whatever delegates you've registered)
 * if your per-message processing is slow it means that there will be N messages fetched from the broker and enqueued locally, your code chewing away on the first message (which also makes it store that message's offset for future commit). As your code progresses, or time, the commit.interval will kick in in the background and commit the offset of the latest message provided to your application.
 * when the commit request is done, a offset_commit event is enqueued on the same queue as the messages
 * this means you need to process a bunch of messages until you get to the offset_commit event in the queue and let it trigger the onOffsetCommit delegate
 * and since your message processing is slow it also means that the onOffsetCommit return channel is slow, but not necessarily the offset commits themselves. E.g., by the time you get your first onOffsetCommit callback it might actually have committed 10 more offsets in the background.

@mhowlett Can you verify this behaviour with regards to consumer_poll() and delegate triggering?

**Comment by mhowlett** [comment] 2017-02-01 22:59
I can verify that offsets do actually get committed to Kafka every 5s, but the OnOffsetCommit event is not getting called (as you suspected @magnus)

Another thing worth mentioning: when I exit out of the the consume loop at an arbitrary time prior to all messages being consumed (causing Consumer.Dispose to be called, causing rd_kafka_consumer_close and rd_kafka_destroy to be called), the OnOffsetCommit event gets raised for every commit that was made. I'm guessing that must be a side effect of rd_kafka_consumer_close, but haven't looked into it this much (and I'm about to go to a meeting). The surprised me.

Note that when using .Poll to consume, Confluent.Kafka doesn't start any additional threads. Everything is on the main thread.

**Comment by edenhill** [comment] 2017-02-02 09:03
If previously queued OnOffsetCommit callbacks were purged when a new one was enqueued then the application would never see it in this case where msg processing is slow, I think that behaviour is worse.

An alternative would be to prioritize OnOffsetCommit on the queue, but I believe there is value in keeping sequenciality. In particular this would mean that the application could get an OnOffsetCommit before it had seen that message in question (since offsets are stored-for-commit when message is passed from librdkafka to delegate queue).

**Comment by mhowlett** [comment] 2017-02-02 17:31
Yeah, definitely OnOffsetCommit callbacks should not be purged when a new one is enqueued - my surprise was that any got called on Consumer.Dispose (but I don't have a good opinion on whether i like that or not - just noting my surprise).

If commit callback events were prioritized based on offset + 1 (another alternative: offsets are stored-for-commit *after* the delegate completes), I think there would be no ordering problems using a prioritized queue. I'm interested in understanding more the downside in doing that. Perf overhead obviously, but perhaps not significant. Related, I noticed MQTT also considers messages delivered on calling (rather than completion) of the delegate, so librdkafka is not alone in that.

If we don't change anything (I suspect we won't), I'll make sure this behavior is documented well.

**Comment by bschmidtbauer** [comment] 2017-02-02 18:06
Let me know if I'm interpreting what @mhowlett & @edenhill are saying here is incorrect, but the way it sounds is that there is not an at-least-once guarantee while using enable.auto.commit == true.

For example, my consumer writes to a DB, that DB is getting patched and my calls fail, I enter a retry loop on processing that message for N minutes and at some point during that time the consumer crashes. Is it possible it had queued message deliveries that were also staged for commit and the commit happened since it is processed on a different thread and the auto commit interval was exceeded?

If so - is there a recommended approach to retries that would alleviate this?  Is just committing offsets manually the correct approach when you need at least once delivery?

**Comment by edenhill** [comment] 2017-02-02 19:14
@mhowlett consumer_close() will finish off any remaining business while bringing down a consumer, including final offset commits, and will thus trigger those callbacks as well. This means that consumer_close() is a potentially blocking call.

**Comment by edenhill** [comment] 2017-02-02 19:20
@bschmidtbauer All clients stores the offset to commit just prior to handing the message to the application, and as you say this may cause message loss (or skip) if you are unfortunate. The counter-policy is to commit (or store-offset-to-commit) after message processing which risks message duplicates in the case of a crash.

There are two ways to do the latter:
 * set `enable.auto.commit=false` and manually commit after message processing (preferably async every N messages or T seconds to maintain performance)
 * set `enable.auto.offset.store=false` but leave `enable.auto.commit=true` - the offset store() locally "stores" the next offset to commit, and with enable.auto.commit in-place that will be every `auto.commit.interval.ms`.

More info here (search for those two properties):
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

And this:
https://github.com/edenhill/librdkafka/issues/826#issuecomment-252901186

offset_store() is not currently exposed in the .NET client but we'll be happy to add it if you decide that's the best fit for your use-case.

**Comment by bschmidtbauer** [comment] 2017-02-10 13:42
@edenhill thanks for the info.  After reviewing this I think it would be really nice to utilize the second option you gave of setting ```enable.auto.offset.store=false``` and then exposing the ```offsets store``` API.

Would the offset store API then take the ```msg.TopicPartitionOffset``` property where msg is the message handed to the ```OnMessage``` delegate?

For the scenarios where at-least-once guarantees are critical the above seems like a much simpler option for the client than to try and ensure they have a task that manually commits the offsets.

**Comment by abhishekakumar** [comment] 2017-04-14 23:50
@edenhill  - Once we have this enhancement completed, can someone add a simple example as well on how to use the new offset store and handle commits. I am unable to visualize how to add offsets into store after processing each message and then consume commitasync to commit the offset.

**Comment by edenhill** [comment] 2017-04-15 07:06
@mhowlett This is a feature request to add support for offset_store()

**Comment by vinodres** [comment] 2017-08-08 20:39
Just wondering when this feature will be available?

**Comment by edenhill** [comment] 2017-08-08 21:06
For reference, the StoreOffsets() API in the Go client: 
https://github.com/confluentinc/confluent-kafka-go/commit/e093d2be7dd0f3fc41f3a53c5127a139a9e4919d

**Comment by mhowlett** [comment] 2017-08-08 21:13
This had fallen off my radar, thanks for the reminder. At this point I've added a help wanted tag meaning I'll be happy to review a PR :-)

**Comment by vinodres** [comment] 2017-08-14 20:39
@mhowlett : Is there any Contributor License Agreement that I have send before I can start contributing or submit a PR?

**Comment by mhowlett** [comment] 2017-08-14 20:44
this should happen when you open a PR (if you haven't already).

**Comment by vinodres** [comment] 2017-08-30 20:11
@mhowlett, I have a quick question. While I was going thru the source code, I saw a remark for CommitAsync method in Cosumer.cs that says 

> "A consumer which has position N has consumed records with offsets 0 through N-1 and will next receive the record with offset N. Hence, this method commits an offset of <paramref name="message" />.Offset + 1."

Is that applicable to StoreOffsets implementation as well?

**Comment by mhowlett** [comment] 2017-08-30 21:05
yes - everything should be consistent.

**Comment by comdw** [comment] 2017-12-15 09:40
@mhowlett  I'm considering switching back to auto commit in the light of StoreOffsets support, assuming I've understood it correctly.  

Background: Our consumers "acknowledge" received messages out of sequence, hence (with auto commit off) we're locally tracking what's been acked and then on a regular interval working out the latest offsets that can be committed (we can only commit an offset if it and all message prior are "acked").

The benefit of switching to StoreOffsets is that I don't need to maintain my own timer, and can do my check and store offsets if required every time any message is acked, and let the auto commit take care of actually committing on this basis.  **Can you confirm there is no I/O overhead when calling StoreOffsets so this shouldn't affect performance?**  I was also trying to work out when I could get back a result with an error in (vs with explicit Commit which actually calls the broker so makes sense that errors might occur).

**Comment by mhowlett** [comment] 2017-12-15 21:38
@comdw - yes, store offsets just stores in memory and it sounds like this fits your use-case well. 

Errors in auto-commit are exposed at the application level (i.e. via the `Consumer.OnError` event in dotnet) as a warning:
 
https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_cgrp.c#L1921

**Comment by sfrooster** [comment] 2018-03-23 02:37
I have a question which may demonstrate a misunderstanding on my part. We recently switched our dotnet consumers to using autocommit offsets = true and autostore offsets = false and it seems to be working very well for us.

Now I want to do the same thing with our Java consumers, but I can't seem to find the "store offsets manually" feature there.

Is that only a dotnet feature (and I suppose Go from what I read above)?

**Comment by sfrooster** [comment] 2018-03-23 02:49
So I gather that the dotnet client is built on top of librdkafka whereas the Java client is not, and this probably accounts for a difference in feature sets.  If someone could confirm, I'll stop bothering here about the Java client - thanks!

**Comment by mhowlett** [comment] 2018-03-23 09:40
yep, I'm pretty sure this is unique to librdkafka and the Java client doesn't have a comparable feature.

**Comment by mhowlett** [comment] 2018-08-24 21:58
this enhancement discussed was added in 0.11.3

**Closed by mhowlett** 2018-08-24 21:58 UTC
Labels: enhancement, good first issue

**Comment by nehadaga11** [comment] 2020-07-05 08:50
Hi,
Sorry for asking on a closed issue but I figured this would be the best place to ask about my issue. I am trying to use atoreoffsets method and I get memory access violation exception.

My code looks something like this with 'autoOffsetStore =false" in my consumer config settings:

`cr = consumer.consume(token);
message= cr.value.toMessage();
HandleMessage(message);
consumer.StoreOffsets(cr);`

But as soon as I reach the StoreOffsets() I get memory access violation error:

`System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.`

I am very new to Kafka and can't figure out what could be causing this issue.

**Comment by sfrooster** [comment] 2020-07-05 10:46
I haven't looked at these API's in awhile, but the first item I noticed is that `ConsumeResult<K,V>.Value` appears to be obsolete and you should instead be using `ConsumeResult<K,V>.Message.Value`

There are other oddities in your message which may be inconsequential (the casing seems wrong, I'm not sure where `toMessage` is coming from, meaning I'm not sure what `message` looks like, and that makes it very difficult to guess what might be going on in `HandleMessage(message)`), but may not.

May I suggest you:
- fix the issue with the obsolete property
- if the problem persists, post here again including more of your code (especially HandleMessage) as well as more of the stack trace?

My barely-informed first guess is that your problem lies somewhere in here:
`message= cr.value.toMessage(); HandleMessage(message);`

**Comment by nehadaga11** [comment] 2020-07-06 13:16
Thanks for the reply. toMessage is our internal method that converts the message to desired object. But that doesn't seem to be the issue. I changed the code to thebelow but I am still getting the same error:
` while (!_cancellationTokenSource.IsCancellationRequested)
                        {
                            try
                            {
                                var cr = consumer.Consume(_cancellationTokenSource.Token);
                                consumer.StoreOffset(cr.TopicPartitionOffset);                                
                            }
                            catch (Exception e)
                            {
                                _logger.LogError($"Error occured: {e.Message}");
                            }`
there is nothing much in the stacktrace either:
   at Confluent.Kafka.Impl.NativeMethods.NativeMethods.rd_kafka_offsets_store(IntPtr rk, IntPtr offsets)
   at Confluent.Kafka.Impl.SafeKafkaHandle.StoreOffsets(IEnumerable`1 offsets)
   at Confluent.Kafka.Consumer`2.StoreOffset(TopicPartitionOffset offset)
   at MyProj.Kafka.StreamOfEntitiesFromKafka`1.Init() in C:\Git\my-project\src\MyProj\Kafka\StreamOfEntitiesFromKafka.cs:line 126
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by sfrooster** [comment] 2020-07-07 04:22
You really should include as much of your code as possible. A few thoughts come to mind:
- You're mixing 64 bit and 32 bit libraries. If you're running this in VS, try setting Run64BitRuntime to false. Also, look at setting the Platform to Active(x86) instead of Active(Any CPU).
- Without seeing all of your code, it's difficult to say, but this can happen if (somehow) your consumer has been disposed when you call StoreOffset
- if you are using VS, try running in debug mode and enabling debugging on unmanaged code (there's a checkbox on the debug tab) as this may give some insight into what the issue is
