### ISSUE TITLE
Thousands of  error messages per day

### ISSUE THREAD

**Issue by Ram80** [confluentinc/confluent-kafka-dotnet#1301] opened 2020-05-28 17:14 UTC
Description
===========
Hi Team,

We are using authenticated Kafka using key tabs, the authentication is successful and able to consume messages. But every 2 minutes it logs a bunch of below errors, and our monitoring tools generating false alarms as the source is stderr and generating more than 1000-1500 in 5 minutes

source":"stderr",
"log":"%5|1590684389.986|LIBSASL|Bank-Prod#producer-1| [thrd:sasl_ssl://edge03.dl.internalload.Bank.com:6767/bootstrap]: sasl_ssl://edge03.dl.internalload.bank.com:6767/1001: GSSAPI client step 1"

source":"stderr",
"log":"%5|1590684389.986|LIBSASL|Bank-Prod#producer-1| [thrd:sasl_ssl://edge03.dl.internalload.Bank.com:6767/bootstrap]: sasl_ssl://edge03.dl.internalload.bank.com:6767/1001: GSSAPI client step 2"

How to reproduce
================
Consumer and producer are up and running fine, we don't have any issues. Only issues logging a bunch of false error messages from the library

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.

	private ProducerConfig CreateProducerConfig()
        {
            ProducerConfig producerConfig = new ProducerConfig()
            {
                ClientId = _kafkaOptions.ClientId,
                ApiVersionRequest = true,
                BootstrapServers = _kafkaOptions.Authenticated.Brokers,
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SaslKerberosServiceName = _kafkaOptions.Authenticated.KerberosServiceName
            };

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                producerConfig.SaslMechanism = SaslMechanism.Gssapi;
                producerConfig.SslCaLocation = _kafkaOptions.Authenticated.CaFilePath;
            }
            else
            {
                // Linux and MacOS
                producerConfig.SaslKerberosKeytab = _kafkaOptions.Authenticated.KeyTabFilePath;
                producerConfig.SaslKerberosPrincipal = _kafkaOptions.Authenticated.Principal;
            }

            return producerConfig;
        }

        private ConsumerConfig CreateConsumerConfig()
        {
            ConsumerConfig consumerConfig = new ConsumerConfig();
            consumerConfig.GroupId = "Bank.Staging";
            consumerConfig.AutoOffsetReset = AutoOffsetReset.Earliest;
            consumerConfig.ClientId = _kafkaOptions.ClientId;
            consumerConfig.ApiVersionRequest = true;
            consumerConfig.BootstrapServers = _kafkaOptions.Authenticated.Brokers;
            consumerConfig.SecurityProtocol = SecurityProtocol.SaslSsl;
            consumerConfig.AutoOffsetReset = AutoOffsetReset.Earliest;
            consumerConfig.SaslKerberosServiceName = _kafkaOptions.Authenticated.KerberosServiceName;

            if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
            {
                consumerConfig.SaslMechanism = SaslMechanism.Gssapi;
                consumerConfig.SslCaLocation = _kafkaOptions.Authenticated.CaFilePath;
            }
            else
            {
                // Linux and MacOS
                consumerConfig.SaslKerberosKeytab = _kafkaOptions.Authenticated.KeyTabFilePath;
                consumerConfig.SaslKerberosPrincipal = _kafkaOptions.Authenticated.Principal;
            }

            return consumerConfig;
        }

        public async Task ConsumeSavings(CancellationToken cancellationToken)
        {
            ConsumerConfig consumerConfig = CreateConsumerConfig();
            using (IConsumer<Ignore, string> consumer = new ConsumerBuilder<Ignore, string>(consumerConfig).Build())
            {
                consumer.Subscribe(_kafkaOptions.ConsumeSavingsTopic + (!_environment.IsProduction() ? _kafkaOptions.GroupIdSuffix : ""));

                while (!cancellationToken.IsCancellationRequested)
                {
                    try
                    {
                        ConsumeResult<Ignore, string> consumeResult = consumer.Consume(cancellationToken);
                        ConsumeSavingsModel savings = JsonConvert.DeserializeObject<ConsumeSavingsModel>(consumeResult.Value);
                        string product = savings.GetProductType();

                        if (product.Equals("PERSONAL_LOAN") || product.Equals("BUSINESS_LOAN"))
                        {
                            Guid accountId = savings.GetAccountId();

                            if (!accountId.Equals(Guid.Empty))
                            {

                            }
                            else
                            {

                            }
                        }
                    }
                    catch (ConsumeException ex)
                    {
                        _logger.LogError(LoggingEvents.KafkaConsumptionFailure, ex, "ConsumeSavingsTopic consuming exception");
                    }
                    catch (Exception e)
                    {
                        _logger.LogError(LoggingEvents.ConsumeSavingsTopicGeneralFailure, e, "ConsumeSavingsTopic general failure");
                    }
                }
                //Ensure the consumer leaves the group cleanly and final offsets are committed
                consumer.Close();
                _logger.LogInformation(LoggingEvents.Uncategorized, "Finished consuming ConsumeSavingsTopic topic");
            }
        }

 - [ ] Confluent.Kafka nuget version. - 1.3.0
 - [ ] Apache Kafka version-1.1.1.
 - [ ] Client configuration.
 - [ ] Operating system- Linux .
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)- attached above in description.
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue- Yes creating fake alerts at midnight.

**Comment by edenhill** [comment] 2020-05-28 18:35
Google suggests this might be related to clock skew between client and Kerberos server, or that reverse dns is incorrect, which you can disable by setting this in /etc/krb5.conf:
```ini
[libdefaults]
rdns=false
```

**Comment by Ram80** [comment] 2020-05-28 19:30
Thank you @edenhill! I am running my service in was Fargate container, by any chance do you know where I need to set that?

**Comment by Ram80** [comment] 2020-05-28 19:43
-Djava.security.krb5.conf This file you mean?

**Comment by Ram80** [comment] 2020-05-28 19:55
@edenhill  and am not passing the below line last its a Linux container and am using just key tab and principal in my code. Will that be a problem?

SaslMechanism = SaslMechanism.Gssapi,

**Comment by edenhill** [comment] 2020-05-28 20:11
-Djava.security.. is a Java thing, not relevant to the dotnet client.
You would set that config in `/etc/krb5.conf` in your linux container

**Comment by Ram80** [comment] 2020-05-28 20:12
perfect thank you @edenhill !!

**Comment by Ram80** [comment] 2020-05-28 20:13
@edenhill  how about this line "SaslMechanism = SaslMechanism.Gssapi,"

**Comment by edenhill** [comment] 2020-05-28 20:19
That's what enables Kerberos, you need it.

**Comment by Ram80** [comment] 2020-05-28 20:21
awesome thanks one more time !!I will try this thing and update you @edenhill.

**Comment by anchitj** [comment] 2024-06-04 12:38
Closing as the issue is resolved.

**Closed by anchitj** 2024-06-04 12:38 UTC
