### ISSUE TITLE
Kafka consumer : error on rd_kafka_cgrp_op_serve: assert: rktp->rktp_assigned

### ISSUE THREAD

**Issue by mgrail** [confluentinc/confluent-kafka-dotnet#625] opened 2018-09-15 08:00 UTC
Hi,

First of all, thank you for your work.

I'm experiencing an issue using the following code. My purpose is to consume messages beginning from the latest offset :

`
while(true)
{
    Dictionary<string, object> kafkaConfig = new Dictionary<string, object>()
    {
        {"bootstrap.servers", GetFormattedKafkaUrl(correspondingConfig) },
        {"group.id", Guid.NewGuid().ToString() },
    };		

    using (var consumer = new Consumer<Ignore, byte[]>(kafkaConfig, null, new ByteArrayDeserializer()))
    {
        connectionOpened = true;

        List<TopicPartitionOffset> tpos = new List<TopicPartitionOffset>();

        // Assign all partitions
        tpos = SynchronisationDatas.Select(c => new TopicPartitionOffset("Test", 0, Offset.End)).ToList(); // Forced to describe the problem

        consumer.Assign(tpos);

        // Raised on critical errors, e.g. connection failures or all brokers down.
        consumer.OnError += (_, error)
        => { LogService.Default().Error($"{ThreadName} : OnError : {error}"); connectionOpened = false; };

        // Raised on deserialization errors or when a consumed message has an error != NoError.
        consumer.OnConsumeError += (_, error)
        => { LogService.Default().Error($"{ThreadName} : OnConsumerError : {error}"); connectionOpened = false; };

        while (_isRunning && connectionOpened)
            {
            if (consumer.Consume(out Message<Ignore, byte[]> msg, TimeSpan.FromSeconds(1)))
            {
                // Stuff on message
            }
        }

        consumer.Unsubscribe();
        consumer.Unassign();
    }
}
`

When I consume for more than ~50 minuts (multiple times), I get the following error :

`
15-09-2018  09:39:35 Default Error Consumer : OnError : 192.168.1.2:9092/bootstrap: Disconnected

*** ..\src\rdkafka_cgrp.c:2808:rd_kafka_cgrp_op_serve: assert: rktp->rktp_assigned ***
rd_kafka_t 0000025E286AED90: rdkafka#consumer-3
 producer.msg_cnt 0 (0 bytes)
 rk_rep reply queue: 0 ops
 brokers:
 rd_kafka_broker_t 0000025E2846EC60: :0/internal NodeId -1 in state UP (for 4164.453s)
  refcnt 2
  outbuf_cnt: 0 waitresp_cnt: 0
  0 messages sent, 0 bytes, 0 errors, 0 timeouts
  0 messages received, 0 bytes, 0 errors
  0 messageset transmissions were retried
  0 toppars:
 rd_kafka_broker_t 0000025E2846E050: 192.168.1.2:9092/bootstrap NodeId -1 in state UP (for 2363.765s)
  refcnt 2
  outbuf_cnt: 0 waitresp_cnt: 0
  15 messages sent, 463 bytes, 0 errors, 0 timeouts
  15 messages received, 1424 bytes, 0 errors
  0 messageset transmissions were retried
  0 toppars:
 rd_kafka_broker_t 0000025E2846F870: kafkaserver:9092/0 NodeId 0 in state UP (for 4164.422s)
  refcnt 5
  outbuf_cnt: 0 waitresp_cnt: 0
  1860 messages sent, 238922 bytes, 0 errors, 0 timeouts
  1860 messages received, 283877598 bytes, 0 errors
  0 messageset transmissions were retried
  1 toppars:
   Annonces [0] leader kafkaserver:9092/0
    refcnt 22
    msgq:      0 messages
    xmit_msgq: 0 messages
    total:     0 messages, 0 bytes
 cgrp:
  PFC1 in state up, flags 0x0
   coord_id 0, managing broker kafkaserver:9092/0
  toppars:
 topics:
  Annonces with 1 partitions, state exists, refcnt 2
   Annonces [-1] leader none
 topics:
  Annonces with 1 partitions, state exists, refcnt 2
   Annonces [-1] leader none
    refcnt 1
    msgq:      0 messages
    xmit_msgq: 0 messages
    total:     0 messages, 0 bytes
   desired partitions:

Metadata cache with 1 entries:
  Annonces (inserted 263922ms ago, expires in 636078ms, 1 partition(s), valid)

`

I can't try catch this exception, the application stop directly. Exception is thrown from libkafka.dll.

Thank you very much for your help..

Checklist
=========
Please provide the following information:

 - [ x] Confluent.Kafka nuget version: 0.11.15
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ x] Operating system: Windows 7 
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ x] Critical issue

**Comment by mhowlett** [comment] 2018-09-16 23:14
you shouldn't call `Unsubscribe` after the consumer loop since there is no corresponding `Subscribe` (you are assigning directly). Although you say librdkafka has an issue in `OnError`, my guess is it's the `Unsubscribe` call after the `OnError` causes you to exit the loop that is causing the problem.

Also, you don't need to exit the loop when`OnError` is triggered - you should consider these messages informational - librdkafka will attempt to recover from all errors automatically. Apologies that this isn't better documented (1.0 will address this).

if you are still having problems, please try 0.11.6-RC2.

**Comment by mgrail** [comment] 2018-09-17 07:39
Thank you @mhowlett , I'll try without exiting the loop and without Unsubscribe() call.

@edenhill, I have seen this issue but I didn't think that it was the same behavior because I don't make a new call to Assign() after the Consume() call. If it's a race condition, where should I put the sleep(1) ?

Thank you

**Comment by edenhill** [comment] 2018-09-17 07:52
@mgrail As a workaround, try putting the sleep prior to consumer disposal; i.e., at the end of the using-block.

**Comment by edenhill** [comment] 2018-09-17 07:52
I'm trying to reproduce this issue now.

**Comment by milindl** [comment] 2024-06-25 10:56
Closing this as [librdkafka#1983 is fixed.](https://github.com/confluentinc/librdkafka/issues/1983)

**Closed by milindl** 2024-06-25 10:56 UTC
Labels: investigate further, LOW
