### ISSUE TITLE
regex subscription causes librdkafka to fault

### ISSUE THREAD

**Issue by comdw** [confluentinc/confluent-kafka-dotnet#482] opened 2018-03-28 14:57 UTC
I'm getting reproducible faulting in librdkafka.dll on the consumer side with 0.11.3:

Faulting module name: librdkafka.dll
Exception code: 0xc0000409
Fault offset: 0x00111c45

- This has only started happening since we started tapping into a live stream of data so are now testing with some decent volume. Furthermore it only happens when the consumer is well behind in the topic, therefore trying to catch up as fast as possible.
- When the problem happens the process just crashes and its not possible to debug. The only information available is in the Windows event log and a Windows Error Report is created but it doesn't look to be much use.
- I can reproduce this with the simple code found in the AdvancedConsumer project Poll example, I just point it at my topic and run from the beginning. 
- Once it crashes the first time if I restart the consumer it always crashes within 2 minutes, but its not related to specific messages in the topic as it will easily get past the previous offset it stopped on.
- No logs of interest on the broker side.
- I've tried upgrading (just librdkafka) to 0.11.4-RC2, but no change.

I've been scratching my head for a day experimenting with different things and the only breakthrough I've had is that if I **don't output anything** to the Console in the OnMessage event handler, everything works fine (entire topic of 1.6 million messages is consumed).  What's more bizarre is that I do have "debug" set to "all" so there is plenty of Console output from librdkafka!  If I have even just `Console.WriteLine("*");` in my message handler, it blows up!

The only errors coming out from the debug log are these (regularly seen, and these come out even when everything is working so I don't think this is the issue):

```
7|2018-03-28 14:39:45.145|rdkafka#consumer-1|PROTOERR| [thrd:kafkadev03:9092/3]: kafkadev03:9092/3: Protocol parse failure at 1031386/1048631 (rd_kafka_msgset_reader_v2:802) (incorrect broker.version.fallback?)
7|2018-03-28 14:39:45.145|rdkafka#consumer-1|PROTOERR| [thrd:kafkadev03:9092/3]: kafkadev03:9092/3: product_raw [4] MessageSet at offset 396382 payload size 21245 > 17245 remaining bytes
7|2018-03-28 14:39:45.152|rdkafka#consumer-1|PROTOERR| [thrd:kafkadev03:9092/3]: kafkadev03:9092/3: Protocol parse failure at 2094236/2097237 (rd_kafka_msgset_reader_v2:802) (incorrect broker.version.fallback?)
7|2018-03-28 14:39:45.152|rdkafka#consumer-1|PROTOERR| [thrd:kafkadev03:9092/3]: kafkadev03:9092/3: product_raw [1] MessageSet at offset 392741 payload size 27264 > 3001 remaining bytes
7|2018-03-28 14:39:45.167|rdkafka#consumer-1|PROTOERR| [thrd:kafkadev02:9092/2]: kafkadev02:9092/2: Protocol parse failure at 1032453/1048631 (rd_kafka_msgset_reader_v2:802) (incorrect broker.version.fallback?)
7|2018-03-28 14:39:45.168|rdkafka#consumer-1|PROTOERR| [thrd:kafkadev02:9092/2]: kafkadev02:9092/2: product_raw [3] MessageSet at offset 399982 payload size 25974 > 16178 remaining bytes
```

 - [x] Confluent.Kafka nuget version: 0.11.3
 - [x] Apache Kafka version: 1.0.0 (confluent docker running in Ubuntu)
 - [x] Provide logs (with "debug" : "..." as necessary in configuration)
- [x] Operating system: Windows 10

**Comment by mhowlett** [comment] 2018-03-28 21:34
what client was used to produce the messages into Kafka?

**Comment by comdw** [comment] 2018-03-28 21:48
The same client (Confluent.Kafka 0.11.3) on a different machine.  

The messages are Avro+SR if that makes any difference.  I have also noticed that it seems to work for a .NET Core Console app (all the crashes have been on .NET Framework Console app), though I do need to run it a few more times to be sure.

**Comment by edenhill** [comment] 2018-03-29 06:50
The protocol parse failures at debug level (`7|..`)  are expected and okay (the broker may send partial responses).

**Comment by comdw** [comment] 2018-03-29 09:14
I'm doing various other tests and will update here observations:

- Using .NET Core is rock solid so far, can't reproduce the crash.
- Offloading the Console output to another thread with Task.Run seems to improve things - it takes up to 10 minutes to crash rather than 1-2 mins.  But it does still crash.
- Doing console output outside of the event handlers (i.e. outside of the poll thread) so far does not crash.
- To rule out the messages themselves being the issue, I filled another topic with 20m 1k messages using kafka-producer-perf-test and pointed the consumer at that.  It still crashed.

I didn't mention it before but the topic is using lz4 compression.

**Comment by raycheung** [comment] 2018-04-03 09:17
I've experiencing the same. My little test program exits with code: 0xc0000409 when consuming a topic with lz4 compression, which has messages in plain string keys and values. It just terminate in a few seconds.

**Comment by comdw** [comment] 2018-04-03 10:49
@raycheung, good to know someone else is seeing this too!  Does your test program output to the console?

I'm currently running a test on a topic with no compression and not seeing the issue after about 1 hour.  I'll try other compression types to narrow this down a bit.

**Comment by mhowlett** [comment] 2018-04-03 16:08
@comdw - I assume when you say you tested with .NET Core, you mean on windows? It seems like it could be some sort of memory problem in librdkafka related to lz4 (and that it works on .NET Core and the Console logging behavior may be random symptoms of this). It would surprise me if there were lz4 issues in librdkafka on linux, since that is relatively well used, but seems very plausible on Windows.

I just tried to reproduce with the below, but I see no problem.
- .NET Framework 4.6.1 console app
- Confluent.Kafka v1.0-experimental-2 (still based on librdkafka 0.11.4)

Do you see a problem when running the below?

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Confluent.Kafka;
using Confluent.Kafka.Serialization;

namespace ConsoleApp10
{
    class Program
    {
        static void Main(string[] args)
        {
            var pconfig = new Dictionary<string, object>
            {
                { "bootstrap.servers", "10.200.7.144:9092" },
                { "compression.codec", "lz4" }
            };

            using (var p = new Producer<string, string>(pconfig, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8)))
            {
                for (int i=0; i<2000000; ++i)
                {
                    p.ProduceAsync("testlz4", new Message<string, string> { Key = i.ToString(), Value = i.ToString() + i.ToString() + "sdfs" });
                }
            }

            var cconfig = new Dictionary<string, object>
            {
                { "bootstrap.servers", "10.200.7.144:9092" },
                { "group.id", Guid.NewGuid().ToString() },
                { "auto.offset.reset", "beginning" }
            };

            using (var c = new Consumer<string, string>(cconfig, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8)))
            {
                c.Subscribe("testlz4");

                c.OnRecord += (_, r)
                    => Console.WriteLine(r.Key + " " + r.Value);

                c.OnPartitionEOF += (_, e)
                    => Console.WriteLine("end!");

                while (true)
                {
                    c.Poll(TimeSpan.FromSeconds(10));
                }
            }
        }
    }
}
```

**Comment by comdw** [comment] 2018-04-03 16:38
@mhowlett, yes all the console apps were running in windows, including the .NET Core one.  Incidentally, my framework console app is using 4.7.1.

I've run your code in a 4.6.1 console app and didn't get the problem. However I have had to wait for over 10 minutes to see the issue previously so I'm going to run a longer test.  I'll also narrow down further by ruling out other differences between your test and mine (one other difference is message size - my messages average 1000 bytes).

**Comment by raycheung** [comment] 2018-04-04 05:44
Strange, I'm able to run the following sample fine with .Net 4.7.1 on Windows. Previously I was consuming a topic with lz4 payload produced by another Java program running on Linux (i.e. not using the same library).

https://github.com/raycheung/KafkaTest-dotnet/blob/master/KafkaTest/Program.fs
```
open System
open System.Text
open System.Threading
open Confluent.Kafka
open Confluent.Kafka.Serialization

[<EntryPoint>]
let main argv =
    printfn "%A" argv

    let uuid = Guid.NewGuid().ToString()
    let servers = argv |> Array.toList
    let topic = sprintf "fsharp-testing-topic-%s" uuid
    let pollTimeout = TimeSpan.FromMilliseconds 500.0

    printfn "topic=%s" topic

    let pConfig =
        Map [
            "bootstrap.servers", servers :> obj
            "compression.codec", "lz4" :> obj
        ]

    use producer = new Producer<_, _> (pConfig, new StringSerializer(Encoding.UTF8), new StringSerializer(Encoding.UTF8))
    let pTasks =
        [for i in 1 .. 100000 ->
            let s = i * i
            let vs = [for _ in 1 .. 100 -> sprintf "square=%d;" s]
            producer.ProduceAsync (topic, i.ToString(), String.Concat vs)]


    let cConfig =
        Map [
            "bootstrap.servers", servers :> obj
            "group.id", "ff-data-" + uuid :> obj
            "auto.offset.reset", "earliest" :> obj
        ]

    let loop =
        async {
            use consumer = new Consumer<_,_>(cConfig, new StringDeserializer(Encoding.UTF8), new StringDeserializer(Encoding.UTF8))
            consumer.Subscribe topic
            consumer.OnMessage.Add (fun msg -> printfn "key=%s" msg.Key)
            while true do
                consumer.Poll pollTimeout
        }

    Async.RunSynchronously(loop, 600000)

    0 // return an integer exit code
```

**Comment by mhowlett** [comment] 2018-04-04 16:06
on my machine (Windows 10 running in a VMWare virtual machine on a MBP with Kafka running on the host) the above consumed all 5M message in ~10 minutes with no problem. I'll let this run with increasingly larger numbers of messages throughout today and see if I can hit the problem. thanks @comdw for reporting and your hard work debugging / setting up the test case.

And thanks @raycheung for the F# example, I was thinking just last night we need a better F# example... Do you have any feedback on the API from the perspective of F#? Can you think of anything important that doesn't work well in that language?

**Comment by comdw** [comment] 2018-04-05 08:50
Hmm, that's frustrating.  Just tried this on a Hyper-V Windows 10 VM and don't see the issue either.  We've had the issue on Windows Server 2012 R2 however (running on a cloud hosted VM).

**Comment by mhowlett** [comment] 2018-04-05 15:29
update: I had this running for > 4hrs yesterday, and the problem did not occur.
which cloud provider? i will hopefully get a chance to run some more tests ...

**Comment by comdw** [comment] 2018-04-05 15:40
Rackspace

**Comment by raycheung** [comment] 2018-04-06 01:09
@mhowlett I'm not yet an expert of F# and definitely can't represent anything. :smiley: I found the API straightforward enough and plays nicely with my F# code, however if we have an asynchronous consumer it would be perfect, tracked here: https://github.com/confluentinc/confluent-kafka-dotnet/issues/487.

**Comment by mhowlett** [comment] 2018-04-06 15:57
@raycheung - same comment as #487 - feel free to jot down any pseudo code as to what you think such an API should look like :-), I'll take note.

**Comment by rsethu** [comment] 2018-04-19 00:44
Running into the same issue with the Consumer. .net 4.6.1 with one instance of the consumer running using poll in a windows service, it works fine. If we increase the number of consumer instances to more than 1, it fails after few seconds, or it fails instantaneously while starting the service. If you try to start it n number of times once in while it starts fine and fails after a while ranging from few seconds to minutes.

Initially was using 0.11.4 then tried using 0.11.1 both having the same behavior.

**Comment by rsethu** [comment] 2018-04-20 17:44
@mhowlett @comdw 
We have nailed down what was causing this behavior for us. The Subscribe method we had a regex, to match a list of topics and that is causing heap corruption / above ntdll exception when there are more than 1 consumer instances with a process. 

The issue goes away by not using Regex pattern and specifying the topics explicitly.

**Comment by mhowlett** [comment] 2018-04-20 19:35
cc @edenhill

**Comment by epriale** [comment] 2018-04-24 20:39
We have the same ptoblem on a Windows 10 physical machine with 0.11.4.
The problem arises quickly if the consumer is "on late", while it is harder to reproduce if the consumer has only a few messages to consume.
Switching from lz4 to gzip solved the problem

**Comment by rsethu** [comment] 2018-04-28 00:14
@edenhill  Regex we had "^spo."

**Comment by Nadav-Revuze** [comment] 2020-06-11 10:51
its 2020 ! still not fixed ?

**Comment by edenhill** [comment] 2020-06-12 07:22
Can you provide your original regexps and some example (matched) topic names?

**Comment by Nadav-Revuze** [comment] 2020-06-12 08:08
i saw it as open issue. thats why im asking if there is any progress

**Comment by edenhill** [comment] 2020-06-12 08:16
@Nadav-Revuze If you are experiencing this issue please provide your regexp, the list of topics in the cluster (needed to reproduce), your client and OS version.

**Comment by edenhill** [comment] 2020-07-02 05:25
Fixed in https://github.com/edenhill/librdkafka/pull/2949

**Closed by edenhill** 2020-07-02 05:25 UTC
Labels: MEDIUM, bug, librdkafka
