### ISSUE TITLE
Consumer Unsubscribe with list of topics as argument

### ISSUE THREAD

**Issue by jpsilvagallino** [confluentinc/confluent-kafka-dotnet#837] opened 2019-03-20 14:07 UTC
Description
===========
Hi,

As suggested in multiple places, I'm trying to reuse a consumer for different client applications. That means the same consumer can subscribe to different topics, depending on the clients on top. The API provides a Subscribe(List<string> topics) method for that purpose. 

Ideally (for my use case), when all clients for a topic are closed, the consumer should be able to **unsubscribe from that topic only**, whilst still be able to consume to from the other topics in the list. However, there is no equivalent method in the API to Unsubscribe(List<string> topics). The API is unbalanced in that regard.

Please correct me if I'm wrong, but to me this implies that a consumer which no longer has interest in one particular topic (no clients for consuming those messages):

- If no steps are taken, would receive messages from a topic which no one would consume. Particularly problematic for load balancing consumer groups.
- Would need to unsubscribe from all topics, and re subscribe to other topics (very expensive).
- Alternatively, could get all assigned partitions for that topic, and pause them (although I'm unsure if this is semantically equivalent to unsubscribing, i.e., other consumer would get the messages from that partition).

I have reviewed the code and found that _SafeKafkaHandle.cs_ calls _Librdkafka.unsubscribe(handle);_ but I couldn't find any function in librdkafka which would take the topic (admittedly, I didn't search too deep). The requested functionality is also not available in the Java API (it would also be very nice to have in there), so I cross my fingers expecting that it could be possible to implement without too much hassle.

Really look forward to your thoughts on this.
Regards,
JP

**Comment by alexandery** [comment] 2019-03-20 17:47
+1

**Comment by jpsilvagallino** [comment] 2019-04-12 14:49
Hi, any comments on this? Do you thing it is feasible (in the sense of, does the protocol currently support it)?

**Comment by mhowlett** [comment] 2019-04-12 16:16
The way the API is designed reflects the very high volume data-pipeline / stream processing applications Kafka was designed for. As Kafka has grown in popularity, use cases like yours (if i understand it correctly) are growing in popularity. You can achieve what you want now, but not as ideally as possible. You can expect the API to adapt over time.

Notes:
1. When you subscribe to a collection of topics, you completely replace the current subscription - you don't add additional topics. `Unsubscribe` is pretty much just shorthand for calling `Subscribe` with no topics. The API isn't unbalanced - it just effectively has one method and makes the user keep track of the current subscription set (which you almost certainly want to be doing anyway).
2. Subscribe relates to consumer groups. If your 'clients' (if i understand how you're using that term correctly) operate independently, which I think they are, and you're operating at a level of volume that you need the workload to be distributed, you should be using dedicated consumers for each 'client'. If you need partition alignment between topics and need a group for that, then you'll want to be subscribing and unsubscribing from those particular topics together. Trying to use the one consumer group for orthogonal tasks distributed across machines probably isn't what you want.
3. I think the main area of concern (where what you want to do is appropriate) is with smaller volume scenarios. Here, you just want to be assigning to the topic partitions to read from directly, not using subscribe. `Assign` has the same API as subscribe - you specify the complete set of topic partitions to read from and `Unassign` is pretty much the same as calling `Assign` with an empty set. This is much cheaper than a consumer group rebalance but it's still less than ideal - behind the scenes, librdkafka throws away any cached messages for the current assignment before applying the new assignment. You can also achieve the same thing with Pause and Resume without modifying the assignment set, however librdkafka still unfortunately throws away and re-fetches data in this case as well. librdkafka could be optimized to handle both of these scenarios optimally. This is not optimized now because for traditional use cases of Kafka, this is a small optimization and not a big deal.
4. Right now, you're going to have to live with the inefficiencies. In most practical scenarios, I don't think you're going to find it a problem - librdkafka is super-awesome fast, and even with these inefficiencies, it will still perform well. I would write your software assuming that both the above are going to be optimized in the future, and get a nice surprise if they do get optimized (which i think is likely at some point). You may want to consider tweaking `queued.max.messages.kbytes` to ensure the consumers never cache too much data that you may want to just throw away.

**Comment by jpsilvagallino** [comment] 2019-04-19 17:31
Hi Matt,

Thanks for taking the time to write such an exhaustive reply (and sorry for my late reply in this case). I will give the partition assignment approach a twist in my mind. I will keep your reply as a reference and revisit it from time to time, as it holds a lot of insights that I may be needing in the close future. Thanks.

So, straight to the question, I understand now that I can remove any topic from my list of subscribed topics and send a new "subscribe" request to Kafka with the updated list of topics to achieve the desired un-subscription.

**Closed** 2019-04-19 17:32 UTC
Labels: question
