### ISSUE TITLE
Run time exception librdkafka.dll

### ISSUE THREAD

**Issue by alex687** [confluentinc/confluent-kafka-dotnet#173] opened 2017-05-10 14:58 UTC
Faulting module name: librdkafka.dll, version: 0.0.0.0, time stamp: 0x58f5d30c
Exception code: 0xc0000005
Exception Information:	The thread tried to read from or write to a virtual address for which it does not have the appropriate access.
Fault offset: 0x0000000000052a15

Confluent.Kafka : 0.9.5
librdkafka.redist : 0.9.5

**Comment by treziac** [comment] 2017-05-10 15:07
Could you provide any contexts with this?
What os? What framework? Is this at initialization or during process?

**Comment by alex687** [comment] 2017-05-10 15:15
I am starting multiple process listening to one topic in one group (many partitions). Some of the processes crashed  and some of them continued working.

**OS** : Windows 7 / Windows Server 2012 R2  
**Framework Version** :  v4.0.30319

**Comment by treziac** [comment] 2017-05-10 15:28
Do you have those processes on same machine, and only one consumer by process?

Can you provide your code on creating/subscribing/disposing your consumer? Nobody ever reported this issue so this seems strange, perhaps something done wrong on the disposing or when assigning partitions

How many partitions do you have and how many consumers do you create?
Can you provide any logs (set "debug" to "cgrp,topic") ?

**Comment by alex687** [comment] 2017-05-10 15:39
I have many processes on many machines. About i have same number of consumers and partitions. Note during run time , I've  added more partitions.

I'm creating a consumer and not disposing it until the process(microservice) is stopped. It's like create infinite while and read till the process is stopped.

**Comment by treziac** [comment] 2017-05-10 15:50
We can't do much with this alone. Does it happen when you start or on consumer which where already listening? Is this always on the same machine or random?

I don't think it's a librdkafka problem (people would have reported it), unless you are doing strange things, that's why having your code would be helpful. This error could also be a problem with your hardware or microservices. It would be great if you could provide a case to reproduce the error, and the logs.

Also, what is the boker version? (though it should not impact anything here)

If this was a problem with librdkafka, it would probably have been introduced in 0.9.5 which introduced improvements on win32 threads, you can try with librdkafka.redist 0.9.4 (keep Confluent.Kafka at 0.9.5)

Thanks!

**Comment by mhowlett** [comment] 2017-05-11 08:24
difficult to tell from the information provided. i would guess you're trying to do something incorrectly (or unusual) and this can be fixed. but it's not good for librdkafka to segfault under any situation so it would be good to understand more how this is happening.

providing a snippet of code that is causing the problem would help a lot.

**Comment by comdw** [comment] 2018-03-28 08:59
Wasn't sure whether to start a new topic, but I'm getting reproducible faulting in librdkafka.dll on the consumer side with 0.11.3:

Faulting module name: librdkafka.dll
Exception code: 0xc0000409
Fault offset: 0x00111c45

This has only started happening since we started tapping into a live stream of data so are now testing with some decent volume.  Furthermore it only happens when the consumer is well behind in the topic, therefore trying to catch up as fast as possible.

When the problem happens the process just crashes and its not possible to debug.  The only information available is in the Windows event log and a Windows Error Report is created but it doesn't look to be much use.

What's odd is that it can take a long time for the problem to first occur, but then once it does, with every subsequent restart of the process it crashes again within 30 seconds.  At some point later its harder to reproduce again.  Its possibly related to other I/O (e.g. if I write all received messages to a file it seems more likely I'll hit the problem, but then subsequent restarts with no file writing will often still crash quickly!)

Currently trying to reproduce with the simplest consumer code possible, to isolate our own wrapper code.  If there is anything that can help collect better information let me know (I had all the debug logs turned on at one point but it didn't seem to show anything useful).

**Comment by mhowlett** [comment] 2018-07-31 22:50
any chance this is related to #482?

**Comment by mhowlett** [comment] 2018-07-31 22:58
@comdw - your exception code is different, so this is almost certainly a different issue. this wiki suggests windows system file corruption: http://winwiki.org/exception-code-0xc0000409/

closing since this is the only report, and there are plausible causes. please open a new issue with as much detail/context as possible if the problem persists.

**Closed by mhowlett** 2018-07-31 22:58 UTC

**Comment by comdw** [comment] 2018-08-09 10:12
@mhowlett, I got as far as isolating my issue to LZ4 compression (as reported on #482) and we since switched to use snappy instead.  I'll wait for outcome of 482 and retest LZ4 again in future if I get chance.
