### ISSUE TITLE
VS 2017 Compatibility of confluent-kafka-dotnet 

### ISSUE THREAD

**Issue by jeffreycruzana** [confluentinc/confluent-kafka-dotnet#800] opened 2019-02-26 03:06 UTC
Description
===========
I am still in the process of figuring this out as there will be a high chance that I am doing something wrong. I thought of posting this just in case but I will update this post once I figure it out.

My issue is for some reasons can't seem to to rebuild this solution from VS 2017. 

I am getting these issues. 

- One or more projects are incompatible with .NETCoreApp,Version=v2.1.

- Project Confluent.SchemaRegistry.Serdes is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1). Project Confluent.SchemaRegistry.Serdes supports:
  - net452 (.NETFramework,Version=v4.5.2)
  - netstandard2.0 (.NETStandard,Version=v2.0)			0	

How to reproduce
================

1. Download the confluent-kafka-dotnet solution
2. Open it from VS 2017 and rebuild Confluent.Kafka solution.

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
        The latest version as of 21-Feb-2019
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system: Windows 7 64 bit
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Error Logs
[logs kafka.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/2903582/logs.kafka.txt)

**Comment by mhowlett** [comment] 2019-02-26 17:54
this works for me. I'm not sure what the problem is - i see related threads that suggest the issue might be due to specific versions of VS components you're using: eg: https://github.com/dotnet/core/issues/1114

perhaps try:
- building the `Confluent.Kafka`, `Confluent.SchemaRegistry` and `Confluent.SchemaRegistry.Serdes` projects explicitly in that order.
- re-installing or updating VS 2017.
- re-installing .NET Core 2.1.

**Comment by hooblix** [comment] 2019-02-26 21:06
Sample code does not work for VS 2017. Many namespace such as ConsumerConfig, AutoOffsetReset, ConsumerBuilder, CancellationTokenSource, ConsumeException are not found.

**Comment by mhowlett** [comment] 2019-02-26 22:31
does just building the `Confluent.Kafka` project (i.e. not the solution) work?

**Comment by hooblix** [comment] 2019-02-27 02:39
I tried sample code with VS 2017 and installed Confluent.Kafka 1.0.0-beta3. Now it recognizes the ConsumerConfig, ConsumerBuilder, and ConsumException, but it still does not recognize AutoOffsetResetType.Earliest

**Comment by mhowlett** [comment] 2019-02-27 16:50
`AutoOffsetRestType.Earliest` implies a reference to 1.0.0-beta2. In 1.0.0-beta3, that name changed to `AutoOffsetReset.Earliest`.

**Comment by milindl** [comment] 2024-06-18 12:26
Closing this - please reopen if the issue persists. I see that Matt answered the original question and the version is now at 2.4.0.

**Closed by milindl** 2024-06-18 12:26 UTC
Labels: can't reproduce
