### ISSUE TITLE
Subscribe("TopicName") is not processing messages.

### ISSUE THREAD

**Issue by NicholasFaneDev** [confluentinc/confluent-kafka-dotnet#144] opened 2017-04-13 07:41 UTC
I have written a consumer to a Kafka instance which has a single topic with multiple partitions. When using the .Assign(TopicPartitionOffset) method I am able to consume messages at the specified partition. However when I use Subscribe with the topic name and use a while loop with a poll, I do not receive any messages.

Here is my executing code, please note there are 2 Kafka connections and the 'Source' connection/consumer is the one in question.
![image](https://cloud.githubusercontent.com/assets/6821345/24994944/571a4c82-2070-11e7-8bed-bf9514633592.png)

**Comment by mhowlett** [comment] 2017-04-13 15:29
first, you should put `.Subscribe` after setting the `.OnMessage` handler. In practice this won't be a problem because retrieving the first message will take longer than setting the event handler, but in theory there is the possibility that messages will be consumed before a handler is registered to handle them and they'll be lost.

I suspect your actual problem is that with `.Assign` you're explicitly reading from offset 0. When you subscribe, the offset that reading starts from is determined by `default.topic.config` if there are no committed offsets for the topic and by default this is the end of the topic. see the AdvancedConsumer example for how to set this to `earliest`.

**Closed** 2017-04-14 18:40 UTC
Labels: question

**Comment by NicholasFaneDev** [comment] 2017-04-18 01:02
Unfortunately this doesn't seem to work. I've copied the AdvancedConsumer line for line but trying to read off our Kafka doesn't work with Subscribe.

For reference we are using Kafka 0.8, and we are connecting to the Kafka through the 3 brokers it is providing.

![image](https://cloud.githubusercontent.com/assets/6821345/25110322/7d086794-2426-11e7-92fc-958a99e2a41c.png)

![image](https://cloud.githubusercontent.com/assets/6821345/25110332/8fae7d48-2426-11e7-857c-407d2d4e6ff1.png)

**Comment by mhowlett** [comment] 2017-04-18 01:38
The problem is that this consumer functionality isn't supported by 0.8 Kafka brokers.

https://www.confluent.io/blog/tutorial-getting-started-with-the-new-apache-kafka-0-9-consumer-client/
https://github.com/edenhill/librdkafka/wiki/Consumer-offset-management

**Comment by NicholasFaneDev** [comment] 2017-04-18 07:01
That'd be it, thanks mate.

**Comment by MrCochese** [comment] 2017-06-07 10:30
How did you resolve this issue? I have a 0.8.1.1 cluster where upgrade is not currently an option.

**Comment by NicholasFaneDev** [comment] 2017-06-07 11:04
We solved it by specifying the partition count through config, then iterating consumer.Assign to create the TopicPartitionOffsets

**Comment by ahilis** [comment] 2018-09-11 06:15
Is it possible to get partitions count for a topic dynamically?
