### ISSUE TITLE
How to make Poll() method to read uncommited messages more than once

### ISSUE THREAD

**Issue by issatayev** [confluentinc/confluent-kafka-dotnet#559] opened 2018-06-22 09:22 UTC
Description
===========
Hi,

In my project, I need consumer to be able to process uncommitted offsets until I manually call CommitAsync() method. Uncommitted offsets are being read only once when I start the console app, but then Poll() method never reads uncommitted offsets again. I know that consumer only keeps track of last received offsets. How can I achieve what I am trying to do? Can you please give any suggestions?

How to reproduce
================
Here is my config and code for consumer:

                var consumerConfig = new Dictionary<string, object>
                {
                    { "group.id", "test-consumer-group" },
                    { "bootstrap.servers", _configuration.GetValue<string>("Kafka:BootstrapServers") },
                    { "enable.auto.commit", "false" },
                    { "default.topic.config", new Dictionary<string, object>()
                        {
                            { "auto.offset.reset", "smallest" }
                        }
                    }
                };

                using (var consumer = new Consumer<Null, KafkaRequestMessage>(consumerConfig, null, new RequestMessageDeserializer()))
                {
                    consumer.OnPartitionEOF += (_, end)
                        => Console.WriteLine($"Date: [{DateTime.Now}], Reached the end of topic: [{end.Topic}], partition: [{end.Partition}], next message will be at offset: [{end.Offset}]");

                    consumer.OnError += (_, error)
                        => Console.WriteLine($"Date:[{DateTime.Now}], Error: [{error}]");

                    consumer.OnConsumeError += (_, msg)
                        => Console.WriteLine($"Date:[{DateTime.Now}], Error consuming from topic/partition/offset [{msg.Topic}/{msg.Partition}/{msg.Offset}]: [{msg.Error}]");

                    consumer.OnOffsetsCommitted += (_, commit) =>
                    {
                        Console.WriteLine($"Date: [{DateTime.Now}], [{string.Join(", ", commit.Offsets)}]");

                        if (commit.Error)
                        {
                            Console.WriteLine($"Date: [{DateTime.Now}], Failed to commit offsets: [{commit.Error}]");
                        }

                        Console.WriteLine($"Date: [{DateTime.Now}], Successfully committed offsets: [{string.Join(", ", commit.Offsets)}]");
                    };

                    consumer.OnPartitionsAssigned += (_, partitions) =>
                    {
                        Console.WriteLine($"Date: [{DateTime.Now}], Assigned partitions: [{string.Join(", ", partitions)}], member id: {consumer.MemberId}");
                        consumer.Assign(partitions);
                    };

                    consumer.OnPartitionsRevoked += (_, partitions) =>
                    {
                        Console.WriteLine($"Date: [{DateTime.Now}], revoked partitions: [{string.Join(", ", partitions)}]");
                        consumer.Unassign();
                    };

                    consumer.OnMessage += async (_, msg) =>
                    {
                        Console.WriteLine($"Date: [{DateTime.Now}], Topic: [{msg.Topic}], Partition: [{msg.Partition}], Offset: [{msg.Offset}], Value: [{msg.Value.OperationStepName}]");
                      
                        // This is my custom logic, based on this I decide whether to commit offset or not
                        var response = await Helper.SendRequestAsync(msg.Value);

                        Console.WriteLine($"Date: [{DateTime.Now}], ResultCode from HTTP call: [{response?.Code}]");

                        if (response != null && response.Code >= 0)
                        {
                                Console.WriteLine($"Date: [{DateTime.Now}], Started committing topic/partition/offset: [{msg.TopicPartitionOffset}]");

                                var committedOffsets = consumer.CommitAsync(msg).Result;

                                Console.WriteLine($"Date: [{DateTime.Now}], Committed topic/partition/offset: [{msg.TopicPartitionOffset}]");
                        }
                    };

                    consumer.Subscribe(new string[] { "test" });

                    Console.WriteLine($"Date: [{DateTime.Now}], Subscribed to: [{string.Join(", ", consumer.Subscription)}]");

                    while (true)
                    {
                        consumer.Poll(100);
                    }
                }

Checklist
=========
Please provide the following information:

 - [x] Confluent.Kafka nuget version: 0.11.4
 - [x] Apache Kafka version: kafka_2.11-1.1.0
 - [x] Client configuration: .NET Core 2
 - [x] Operating system: Windows 10
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue

**Comment by issatayev** [comment] 2018-06-24 06:19
I updated to 1.0-experimental-4 and also put { "auto.offset.reset", "smallest" } at the top level, but that didn't help. After message is consumed once and not committed, it is never being consumed again.

**Comment by issatayev** [comment] 2018-06-25 04:42
Maybe I am missing some configuration properties?

**Comment by edenhill** [comment] 2018-06-25 09:08
@issatayev Can you elaborate on what you are trying to do, it is not clear to me what you mean by reading uncommitted messages more than once.
Messages are fetched in order from the last committed offset, or according to auto.offset.reset policy if no previously committed offset. Messages will typically not re-fetched unless you manually seek() or assign() to an older offset.

**Comment by mhowlett** [comment] 2018-06-25 15:41
Kafka does not support this - only one offset is maintained per topic/partition. This omission is by design - it allows for much higher throughput / performance. You'll need to keep track of failed requests via some other mechanism, another kafka topic probably. you might find compacted topics a useful tool for that (since you can remove messages by sending tombstones), but i haven't thought it through fully.

**Closed by mhowlett** 2018-06-25 15:41 UTC
