### ISSUE TITLE
dotnet core (linux) producer fails

### ISSUE THREAD

**Issue by mmp5** [confluentinc/confluent-kafka-dotnet#152] opened 2017-04-19 20:29 UTC
I'm using dotnet core in a CentOS 7 environment and visual studio code.
Zookeeper (cluster) and Kafka (cluster) are working well. 

Confluent.Kafka 0.9.5-RC3 fails when I try to initiate a producer without an exception.

`using (var producer = new Producer<Null, string>(producerConfig, null, new StringSerializer(Encoding.UTF8)))`

I loaded latest git and saw that in the following file the version() function is throwing an exception:
confluent-kafka-dotnet-master/src/Confluent.Kafka/Impl/LibRdKafka.cs
```
if ((long) version() < minVersion) {
                throw new FileLoadException($"Invalid librdkafka version {(long)version():x}, expected at least {minVersion:x}");
            }
```

When I add the following PackageReference the version() function is working but the number is lower than the expected minVersion.
<PackageReference Include="RdKafka.Internal.librdkafka-Linux" Version="0.9.2-ci-54" />

Could you have a look and maybe reproduce on an CentOS7 environment?
thx

**Comment by edenhill** [comment] 2017-04-19 20:35
Can you paste the exception output?

**Comment by mmp5** [comment] 2017-04-19 20:41
The version() function gives the following exception: 
"Unable to load DLL 'librdkafka': The specified module could not be found.\n (Exception from HRESULT: 0x8007007E)"

I also tried w/ and w/o:
<PackageReference Include="librdkafka.redist" Version="0.9.5-RC3" />
<PackageReference Include="RdKafka.Internal.librdkafka-Linux" Version="0.9.2-ci-54" />

When I use in combination Producer init will work but fails when kafka (and zookeeper) are not running (also no exception that could be catched here):
<PackageReference Include="Confluent.Kafka" Version="0.9.4" />
<PackageReference Include="RdKafka.Internal.librdkafka" Version="0.9.2-ci-189" />

**Comment by mhowlett** [comment] 2017-04-19 20:47
duplicate of #150. currently investigating.

**Comment by mhowlett** [comment] 2017-04-21 16:36
closing - tracking in #150.

**Closed by mhowlett** 2017-04-21 16:36 UTC

**Comment by treziac** [comment] 2017-04-24 12:51
@mmp5 
On a side note you should not use RdKafka.Internal.librdkafka (older project) but librdkafka.redist. Did you try with the 0.9.5 version?

If not working , tracking continue on #150
If it was just to test with the other packaging, thanks for this :)
