### ISSUE TITLE
is single consumer instance which has multiple partitions assigned achieved round-robin? 

### ISSUE THREAD

**Issue by lixiandai** [confluentinc/confluent-kafka-dotnet#528] opened 2018-05-03 19:46 UTC
Description
===========
If we have one single instance of consumer which has 3 partitions assigned for specific topic,  when we start to consumer.consume in a loop, does this consumer pick up messages from different partitions randomly or it always consume from one partition until it reach the EOF then switch to next partition?
Assuming we always consume from beginning offset an did not do auto commit offset. 

Thanks. 

How to reproduce
================

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version:
 - [ ] Apache Kafka version: 
 - [ ] Client configuration:
 - [ ] Operating system:
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration)
 - [ ] Provide broker log excerpts
 - [ ] Critical issue
@

**Comment by mhowlett** [comment] 2018-05-03 20:18
order of consumption across partitions is non-deterministic. In practice you'll find the order of messages clumped together by partition for consumers that are 'catching up' (due to message batching and internal operation), but in general the consumer won't read to the end of one partition before returning messages from another.

**Comment by lixiandai** [comment] 2018-05-04 14:04
@mhowlett thanks. it makes sense. one follow up
in Consumer<TKey, TValue> implementation, what is the key difference to call .consume or .poll? i knew if we are using .poll, we have to listen to OnMessage event to grab the output message. Other than this, is there any specific use case for those two methods?

Thanks.

**Comment by mhowlett** [comment] 2018-05-04 17:38
They achieve the same thing. `Consume` exists simply because sometimes it is more convenient to use than registering an event on `OnMessage`. Use whichever is more convenient.

**Comment by lixiandai** [comment] 2018-06-04 18:27
@mhowlett i am facing one issue related to subscribing OnPartitionsAssigned and OnPartitionsRevoked now. Whenever i spin up a new consumer which belong to same consumer group of existing running one, OnPartitionsRevoked will raised and remove all partitions then OnPartitionsAssigned get raised and assign partitions again. This behavior makes our customized code logic too complex now. 

i was thinking if a new consumer join in, we only need to revoke the partition which new consumer picked for the existing consumer. Also we will only need to revoke the dropped partition, but other partitions should not need to be re-assigned again. 

Please let me know if my finding is correct or i did something wrong in our implementation to cause this issue.

**Comment by BenjaminHolland** [comment] 2018-06-08 06:31
@lixiandai 
It looks like the callback for the re-balance event is defined in librdkafka. (see [here](https://github.com/confluentinc/confluent-kafka-dotnet/blob/3f48e8944242abf631ea8d2cd5698f6e149e0731/src/Confluent.Kafka/Impl/LibRdKafka.cs#L368) and [here](https://github.com/confluentinc/confluent-kafka-dotnet/blob/b03c76aad484967afcbf6d125721fc412c073292/src/Confluent.Kafka/Consumer.cs#L756))

I'd agree with you that that would seem most logical workflow, but it doesn't seem to hard to store the consumers assignments on revoke and attach a self-removing delegate that will do the diff calculations for you if you. If things haven't changed since I was last working on this stuff, you have to do something similar for subscribing to a topic at a particular spot.

```
void InterceptAssignments(object sender, List<TopicPartition> assignments)
                {
                    consumer.OnPartitionsAssigned -= InterceptAssignments;
                    var alteredAssignments = from tp in assignments
                                             select new TopicPartitionOffset(tp, tp.Topic.Equals(topic) ? initialPosition : Offset.Invalid);
                    consumer.Assign(alteredAssignments);
                }
consumer.OnPartitionsAssigned += InterceptAssignments;
consumer.Subscribe(topic);
```

It's not hard, just annoying.

**Comment by mhowlett** [comment] 2018-07-27 23:20
prior to v1.0, I will be thinking deeply about re-balancing + discuss in detail with @edenhill. will update this thread following that.

**Comment by IvanZheng** [comment] 2019-05-06 06:39
MaxPartitionFetchBytes(default value:1048576 ) in ConsumerConfig will make consume fetch messages from one partition until reaches the threshold. If set MaxPartitionFetchBytes to 1, consumer can consume messages from multiple partitions round-robin. 
Is it a misusing or does it has any side effects? @mhowlett

**Comment by mhowlett** [comment] 2019-05-06 14:46
this controls the maximum number of bytes returned from a broker for a partition in a fetch request. these requests happen in parallel on different threads for each broker. If you only have one broker, you might indeed get 'round robin', though that's not by design, and I'm not sure. If you have more than one broker you won't get round-robin precisely (since the threads operate independently), but the results won't be clumped. The downside in doing this is efficiency - the best way to get better performance out of Kafka is to increase batching to minimize the number of broker requests, this is doing the opposite.

**Comment by anchitj** [comment] 2024-06-25 12:25
Closing as all the queries are answered

**Closed by anchitj** 2024-06-25 12:25 UTC
Labels: discussion, HIGH
