### ISSUE TITLE
Producer.Flush hangs indefinitely when partition has no leader

### ISSUE THREAD

**Issue by blachniet** [confluentinc/confluent-kafka-dotnet#1027] opened 2019-08-09 11:10 UTC
Description
===========

Calling [`Flush()`](https://docs.confluent.io/current/clients/confluent-kafka-dotnet/api/Confluent.Kafka.IProducer-2.html#Confluent_Kafka_IProducer_2_Flush_CancellationToken_) on a producer hangs indefinitely when the target partition has no leader, regardless of `message.timeout.ms`. Delivery handlers are **not** invoked during this time to indicate local message timeouts. Delivery handlers are not invoked until the partition obtains a leader.

How to reproduce
================

1. Create a 3-broker Kafka cluster following the instructions in the [Kafka Quickstart](https://kafka.apache.org/quickstart).
1. Create a topic with a replication factor of 2 named `my-replicated-topic`
    ```
    $ bin/kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 2 --partitions 1 --topic
    ```
1. Determine which brokers have a partition replica. In the example below, brokers `0` and `1` contain partition replicas. Broker `2` **does not** have a replica of this partition.
    ```
    $ bin/kafka-topics.sh --bootstrap-server localhost:9092 --describe --topic my-replicated-topic
    Topic:my-replicated-topic	PartitionCount:1	ReplicationFactor:2	Configs:segment.bytes=1073741824
	    Topic: my-replicated-topic	Partition: 0	Leader: 1	Replicas: 1,0	Isr: 1,0
    ```
1. Everything should work at this point. You should be able to run [the dotnet application][1] and get output like the following.
    ```
    $ cd my-producer
    $ dotnet run
    Hello World!
    Flushing... (shouldn't take more than 5000ms)
    [✓] Hello world 0
    [✓] Hello world 1
    [✓] Hello world 2
    [✓] Hello world 3
    [✓] Hello world 4
    Flush completed in less than 15000ms.
    ```
1. Now, stop the two Kafka brokers that have replicas of your topic partition. In my example, I need to stop brokers `0` and `1`. I will leave broker `2` running. The goal is to ensure that the partition does not have a leader. In the command below, you can see this via `Leader: none`. You may need to change the `bootstrap-sever` depending on which broker is still available.
    ```
    $ bin/kafka-topics.sh --bootstrap-server localhost:9094 --describe --topic my-replicated-topic
    Topic:my-replicated-topic	PartitionCount:1	ReplicationFactor:2	Configs:segment.bytes=1073741824
	    Topic: my-replicated-topic	Partition: 0	Leader: none	Replicas: 1,0	Isr:
    ```
1. Run [the dotnet application][1] again. You will notice that we do not successfully deliver messages (this is expected). The problems are that 1) we don't receive any failed delivery reports and 2) the call to `Flush()` does not respect the `MessageTimeoutMs`.
    ```
    $ dotnet run
    Hello World!
    [ProducerError] localhost:9093/bootstrap: Connect to ipv6#[::1]:9093 failed: Connection refused (after 1ms in state CONNECT)
    Flushing... (shouldn't take more than 5000ms)
    Flush DID NOT complete after 15000ms!
    ```

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file. **See [this Gist][1]**
 - [x] Confluent.Kafka nuget version. **1.1.0**
 - [x] Apache Kafka version. **kafka_2.3.0**
 - [x] Client configuration.
    ```c#
            var producerConfig = new ProducerConfig
            {
                BootstrapServers = "localhost:9092,localhost:9093,localhost:9094",
                MessageTimeoutMs = 5000,
            };
    ```
 - [x] Operating system. **OSX & Windows**
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

[1]: https://gist.github.com/blachniet/2f091c5e2f7c21ba590b0f7e533768dd

**Comment by blachniet** [comment] 2019-08-09 11:48
For kicks, I tried this scenario out in Python. See [the `.py` file in the same Gist][1]. I got the same results: the call to flush hangs until a new leader is assigned, regardless of `message.timeout.ms`. If a new leader eventually does come online, delivery callbacks are finally executed indicating indicating that the message timed out.

Could this be a problem in the underlying `librdkafka`?

[1]: https://gist.github.com/blachniet/2f091c5e2f7c21ba590b0f7e533768dd#file-confluentkafkaproducerhangsonflush-py

**Comment by mhowlett** [comment] 2019-08-09 16:45
yep, sounds like a bug - thanks for the detailed report. cc: @edenhill

**Comment by blachniet** [comment] 2019-08-09 17:31
@mhowlett & @edenhill: Should I move this to the [librdkafka](https://github.com/edenhill/librdkafka) project, or is it best left here for now?

**Comment by edenhill** [comment] 2019-08-12 08:04
Can't reproduce this:
```
$ $KAFKA_PATH/bin/kafka-topics.sh --describe --bootstrap-server $BROKERS  --topic xx1
[2019-08-12 10:02:12,482] WARN [AdminClient clientId=adminclient-1] Connection to node -3 (/0.0.0.0:55493) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
[2019-08-12 10:02:12,486] WARN [AdminClient clientId=adminclient-1] Connection to node -2 (/0.0.0.0:55491) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
Topic:xx1	PartitionCount:1	ReplicationFactor:2	Configs:
	Topic: xx1	Partition: 0	Leader: none	Replicas: 4,3	Isr:

$ python hang.py
Flushing...
Message delivery failed: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Broker: Unknown topic or partition"}
Message delivery failed: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Broker: Unknown topic or partition"}
Message delivery failed: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Broker: Unknown topic or partition"}
Message delivery failed: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Broker: Unknown topic or partition"}
Message delivery failed: KafkaError{code=UNKNOWN_TOPIC_OR_PART,val=3,str="Broker: Unknown topic or partition"}
```

Could you reproduce this with `debug=all` and provide the logs?

**Comment by blachniet** [comment] 2019-08-12 16:52
Hi @edenhill,

Since you referred to the Python producer, I grabbed logs from that one. Let me know if you'd like similar logs from the dotnet producer. See [`pyproducer.log` in the same gist](https://gist.github.com/blachniet/2f091c5e2f7c21ba590b0f7e533768dd#file-pyproducer-log). 

In these logs, the two brokers containing the two partitions of the topic are down (`0` ==`:9092` and `1` == `:9093`). 

```
$ bin/kafka-topics.sh --bootstrap-server localhost:9094 --describe --topic my-replicated-topic
Topic:my-replicated-topic	PartitionCount:1	ReplicationFactor:2	Configs:segment.bytes=1073741824
	Topic: my-replicated-topic	Partition: 0	Leader: none	Replicas: 1,0	Isr:
```

That log just contains the `stderr`. Here's what I ran. I stopped the application after ~20 seconds.

```
$ python ConfluentKafkaProducerHangsOnFlush.py 2> producer.log
Flushing...
^Z
[2]  + 21233 suspended  python producer.py 2> producer.log
```

I also added my broker configuration files to the gist, in case they are helpful: [`server.properties`](https://gist.github.com/blachniet/2f091c5e2f7c21ba590b0f7e533768dd#file-server-properties), [`server-1.properties`](https://gist.github.com/blachniet/2f091c5e2f7c21ba590b0f7e533768dd#file-server-1-properties) and [`server-2.properties`](https://gist.github.com/blachniet/2f091c5e2f7c21ba590b0f7e533768dd#file-server-2-properties). These are modified minimally, as instructed by the Kafka Quickstart article.

In your results, is `UNKNOWN_TOPIC_OR_PART` an expected error in this situation? I thought it would have emitted an local message timeout error instead, after it had tried delivering for the configured timeout.

**Comment by blachniet** [comment] 2019-08-12 17:15
I collected another set of logs: [`myproducer-2.log`](https://gist.github.com/blachniet/2f091c5e2f7c21ba590b0f7e533768dd#file-myproducer-2-log). In this situation, I  started the producer while the two brokers containing the two partitions of the topic were down (same as before).

```
$ bin/kafka-topics.sh --bootstrap-server localhost:9094 --describe --topic my-replicated-topic
Topic:my-replicated-topic	PartitionCount:1	ReplicationFactor:2	Configs:segment.bytes=1073741824
	Topic: my-replicated-topic	Partition: 0	Leader: none	Replicas: 1,0	Isr:
```

I let this go on for 30 seconds. As a reminder, the `message.timeout.ms` is set to `5000`. After 30 seconds, I turned on broker 0 (`:9092`). You can see it coming online in the logs around line 697.

After the broker eventually fired up, the producer received the message deliver callbacks with errors for `MSG_TIMED_OUT`. I added timestamps to the `stdout` output to help show the time difference between the prints (see the [updated Python script in the gist][1]).

```
$ python ConfluentKafkaProducerHangsOnFlush.py 2> producer.log
|1565629330.707| Flushing...
|1565629365.914| Message delivery failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
|1565629365.914| Message delivery failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
|1565629365.914| Message delivery failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
|1565629365.914| Message delivery failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
|1565629365.914| Message delivery failed: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}
```

[1]: https://gist.github.com/blachniet/2f091c5e2f7c21ba590b0f7e533768dd#file-confluentkafkaproducerhangsonflush-py

**Comment by edenhill** [comment] 2019-08-13 11:06
Thank you!

Reproduced and fixed in this PR:
https://github.com/confluentinc/confluent-kafka-dotnet/issues/1027

**Comment by mhowlett** [comment] 2019-08-13 22:51
closing this as there's now a PR open with a fix - thanks for bringing this to our attention. it'll be resolved in the next release.

**Closed by mhowlett** 2019-08-13 22:51 UTC
Labels: bug
