### ISSUE TITLE
Cannot produce / consume tombstone message

### ISSUE THREAD

**Issue by michael-huxtable** [confluentinc/confluent-kafka-dotnet#905] opened 2019-04-24 06:55 UTC
Description
===========

You cannot produce/consume a `null` message with the `AvroSerializer`, to a produce a `null` message then a specific producer needs to be used with the value serializer set as `Serializers.Null`.

So far using the `AvroDeserializer` , I have not found a way to consume these `null` messages, currently when doing this I get the following exception:

```
Confluent.Kafka.ConsumeException: Local: Value deserialization error ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.ReadByte()
   at Confluent.SchemaRegistry.Serdes.SpecificDeserializerImpl`1.Deserialize(String topic, Byte[] array)
   at Confluent.SchemaRegistry.Serdes.AvroDeserializer`1.DeserializeAsync(ReadOnlyMemory`1 data, Boolean isNull, SerializationContext context)
   at Confluent.Kafka.Consumer`2.<>c__DisplayClass71_0.<<ConsumeViaBytes>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Confluent.Kafka.Consumer`2.ConsumeViaBytes(Int32 millisecondsTimeout)
   --- End of inner exception stack trace ---
```

How to reproduce
================

Use a specific producer for building tombstone messages:

```
var tombstoner = new ProducerBuilder<int, Null>(_kafkaConfiguration.ProducerConfiguration)
	.SetKeySerializer(new AvroSerializer<int>(_schemaRegistryClient))
	.SetValueSerializer(Serializers.Null)
	.Build();

var tasks = properties.Select(property => tombstoner.ProduceAsync("test-topic",
	new Message<int, Null>
	{
		Key = 1,
		Value = null,
		Timestamp = Timestamp.Default
	}));
```

The consumer code is as the examples on the GitHub homepage, it's currently the simple consumer example. Single partition, etc. The other non-null messages get handled fine. A `ConsumeException` is thrown for the `null` messages.

Checklist
=========

Please provide the following information:
 - [Y] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [1.0.0-RC3] Confluent.Kafka nuget version.
 - [Kafka 2.0.1-L0 (Landoop)] Apache Kafka version.
 - [N] Client configuration.
 - [Windows 10 x64] Operating system.
 - [N] Provide logs (with "debug" : "..." as necessary in configuration).
 - [N] Provide broker log excerpts.
 - [N] Critical issue.

**Comment by mhowlett** [comment] 2019-04-24 10:46
thanks for pointing that out. in the java avro serdes, `null` is handled as a special case, but in the .net serdes, we don't have that logic. as a workaround for now, I suggest just wrapping our avro serdes and handling `null` in your wrapper (it will be a small number of loc). 

https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java#L56

**Comment by mapuglisi** [comment] 2019-05-30 13:53
I'm having a related issue.

I'm trying to consume a topic tombstone (Serialized key, null value) and the AvroDeserializer just breaks with an `Unhandled consumer error: Local: Value deserialization error` which has as an inner exception: `System.ArgumentNullException` and message: `Buffer cannot be null.`

I'm logging errors and effectively the message received was correct:

```
"Message": {
      "Key": "AAAAAm8AFENVV1NQSUNVUjEA8AQ=",
      "Value": null,
      "Timestamp": {
        "Type": 1,
        "UnixTimestampMs": 1558523287993,
        "UtcDateTime": "2019-05-22T11:08:07.993Z"
      },
      "Headers": []
    }
```

**Comment by CautiousMarmoset** [comment] 2019-08-16 15:18
We are facing a similar issue where we rely on tombstone messages as well to indicate deletes on a topic. Would love to see this enhancement gain some traction.

**Comment by rsaltrelli** [comment] 2020-04-13 18:53
> thanks for pointing that out. in the java avro serdes, `null` is handled as a special case, but in the .net serdes, we don't have that logic. as a workaround for now, I suggest just wrapping our avro serdes and handling `null` in your wrapper (it will be a small number of loc).
> 
> https://github.com/confluentinc/schema-registry/blob/master/avro-serializer/src/main/java/io/confluent/kafka/serializers/AbstractKafkaAvroSerializer.java#L56

Is there an ETA on when this will be fixed?  We're trying to consume data from a topic created by Debezium.  It works fine when `before` and `after` both exist but tombstones (`after` == null) result in the following exception.

```
at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at Confluent.SchemaRegistry.Serdes.SpecificDeserializerImpl`1.Deserialize(String topic, Byte[] array)
   at Confluent.SchemaRegistry.Serdes.AvroDeserializer`1.DeserializeAsync(ReadOnlyMemory`1 data, Boolean isNull, SerializationContext context)
   at Confluent.Kafka.SyncOverAsync.SyncOverAsyncDeserializer`1.Deserialize(ReadOnlySpan`1 data, Boolean isNull, SerializationContext context)
   at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
   --- End of inner exception stack trace ---
   at Confluent.Kafka.Consumer`2.ConsumeImpl[K,V](Int32 millisecondsTimeout, IDeserializer`1 keyDeserializer, IDeserializer`1 valueDeserializer)
   at Confluent.Kafka.Consumer`2.Consume(TimeSpan timeout)
   at TCGplayer.Foundation.EventBus.Kafka.KafkaEventSubscriber`2.<>c__DisplayClass19_0.<ExecuteAsync>b__0()
```

Looks like the problem is [here](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.SchemaRegistry.Serdes.Avro/SpecificDeserializerImpl.cs#L112).

**Closed** 2022-02-16 20:21 UTC
Labels: enhancement
