### ISSUE TITLE
Access Violation exception when running as a service

### ISSUE THREAD

**Issue by ashishbhatia22** [confluentinc/confluent-kafka-dotnet#334] opened 2017-10-10 15:03 UTC
Description
===========
When hosting a consumer as a windows service (using TopShelf), I am getting an access violation exception. Code works fine when running as  a console program. 

Exception Info: System.AccessViolationException
   at Confluent.Kafka.Impl.LibRdKafka+NativeMethods.rd_kafka_subscribe(IntPtr, IntPtr)
   at Confluent.Kafka.Impl.SafeKafkaHandle.Subscribe(System.Collections.Generic.IEnumerable`1<System.String>)
   at Confluent.Kafka.Consumer.Subscribe(System.String)

I tried running the service as an admin. However, I still see the access violation exception.

**Comment by treziac** [comment] 2017-10-10 15:26
I never used topshelf, but you are probably dealing with #107 : it seems you are directly disposing your consumer before subscribing
Could you provide some reproductible code? We can't help from just those informations

**Comment by ashishbhatia22** [comment] 2017-10-10 15:51
I get this exception when we start the service. On start of service, I am setting a reader to the kafka topic. I am pasting the snippet below. Please note that when i run this from visual studio, everything works fine. We only see this when the code is installed as service. Exception details:

Exception Info: System.AccessViolationException
   at Confluent.Kafka.Impl.LibRdKafka+NativeMethods.rd_kafka_subscribe(IntPtr, IntPtr)
   at Confluent.Kafka.Impl.SafeKafkaHandle.Subscribe(System.Collections.Generic.IEnumerable`1<System.String>)
   at Confluent.Kafka.Consumer.Subscribe(System.String)

Code:

-- Start of service
    Task.Factory.StartNew(() => reader.ReadMessage(readTopic));
-- Reader here is  our custom class
  public bool BeginRead(string topicName, string groupId, ITargetBlock<LGMessage> target)
        {
            targetBuffer = target;

            Run_Poll(topicName);

            return true;
        }
  public void Run_Poll(string topics)
        {
            try
            {
                sw = Stopwatch.StartNew();

                MessageConsumer.OnMessage += Consumer_OnMessage;

**Comment by ashishbhatia22** [comment] 2017-10-11 13:12
I was able to fix this after removing IDisposable interface on the classes that instantiated KafkaConsumer object. I am still investigating if we get the same behavior when we host the code in IIS.

**Comment by mhowlett** [comment] 2018-07-31 16:02
in newer versions of the library, access violation exception's that were occurring due to an attempt to use a disposed consumer (librdkafka handle) should now produce object disposed exceptions. If access violation exceptions are still occurring in the above scenario with 0.11.5, that is an indication this is a different problem. I'm closing this under the assumption the problem is using a disposed consumer, however if access violation exceptions are still occurring with 0.11.5, please re-open.

**Closed by mhowlett** 2018-07-31 16:02 UTC

**Comment by mekk1t** [comment] 2022-07-04 07:38
For me, the problem was that I subscribed to `NULL` topic. Like:
```csharp
consumer.Subscribe(null);
```

So it was a configuration problem. I'll leave it here in case it helps anyone since I myself stumbled upon this issue.

**Comment by mhowlett** [comment] 2022-07-04 22:43
@mekk1t - a check for that was put in a couple of years ago - suggest upgrading, there are many other fixes and improvements as well.
