### ISSUE TITLE
Can not subscribe to a topic with more than 1 partition when using Confluent.Kafka v2.2.0 in  .NET Framework

### ISSUE THREAD

**Issue by MasoudKarimi92** [confluentinc/confluent-kafka-dotnet#2089] opened 2023-07-30 06:57 UTC
Description
===========
It seems there is a bug when using Confluent.Kafka v2.2.0  in .NET Framework projects. When I want to subscribe to a topic with more than 1 partition it always crashes at Subscribe() method. There is no problem in using this package with  .NET Core and .NET 6 or 7 projects. Also when I downgraded the package to v2.1.1 the issue resolved. Here is the error in v2.2.0  in .NET Framework projects:

_**rd_tmpabuf_alloc0: rd_kafka_topic_info_new_with_rack:1860: requested size 16 + 5 > 20**_

How to reproduce
================
1 - run kafka on docker
2- Create a topic with more than one partition, for example 3 partitions:
`kafka-topics --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 3 --topic test` 
3- produce some message in this topic
4- write a simple console app in .NET Framework which tries to subscribe to this topic and consume messages
the app will crash at Subscribe()

here is my code for consumer:

`var config = new ConsumerConfig
            {
                BootstrapServers = "localhost:9092",
                GroupId = "kafka-dotnet-getting-started",
                AutoOffsetReset = AutoOffsetReset.Earliest
            };

            const string topic = "test";

            CancellationTokenSource cts = new CancellationTokenSource();
            Console.CancelKeyPress += (_, e) => {
                e.Cancel = true; // prevent the process from terminating.
                cts.Cancel();
            };

            using (var consumer = new ConsumerBuilder<string, string>(
                config).Build())
            {
                consumer.Subscribe(topic);
                try
                {
                    while (true)
                    {
                        var cr = consumer.Consume(cts.Token);
                        Console.WriteLine($"Consumed event from topic {topic} with key {cr.Message.Key,-10} and value {cr.Message.Value}");
                    }
                }
                catch (OperationCanceledException)
                {
                    // Ctrl-C was pressed.
                }
                catch (Exception ex)
                {

                }
                finally
                {
                    consumer.Close();
                }
`

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [x] Client configuration.
 - [ ] Operating system.
 - [x] Provide logs (with "debug" : "..." as necessary in configuration).
 - [x] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by glazkovalex** [comment] 2023-08-18 13:06
I confirm the presence of a problem in version 2.2.0 at .Net 7.0!

When trying to publish to the topic "sample", an error 'Access violation' occurs: rd_tmpabuf_alloc0: rd_kafka_topic_info_new_with_rack:1860: requested size 16 + 7 > 20.
When trying to publish to the topic "sample-topic", an error 'Access violation' occurs: rd_tmpabuf_alloc0: rd_kafka_topic_info_new_with_rack:1860: requested size 16 + 13 > 28.
But with the name of the topic "sample-8", the subscription works for some reason!

My test:

        // Given
        const string topic = "sample";
        var bootstrapServer = _kafkaContainer.GetBootstrapAddress();
        var producerConfig = new ProducerConfig
        {
            BootstrapServers = bootstrapServer,
        };
        var consumerConfig = new ConsumerConfig
        {
            BootstrapServers = bootstrapServer,
            GroupId = "sample-consumer",
            AutoOffsetReset = AutoOffsetReset.Earliest,
        };
        var message = new Message<string, string> { Value = Guid.NewGuid().ToString("D") };

        // When
        ConsumeResult<string, string> consumeResult;
        using (var producer = new ProducerBuilder<string, string>(producerConfig).Build())
        {
            var deliveryResult = await producer.ProduceAsync(topic, message).ConfigureAwait(false);
        }

        using (var consumer = new ConsumerBuilder<string, string>(consumerConfig).Build())
        {
            consumer.Subscribe(topic);
            consumeResult = consumer.Consume(TimeSpan.FromSeconds(15));
        }

        // Then
        Assert.Equal(message.Value, consumeResult.Message.Value);

**Comment by bsimovic** [comment] 2023-09-14 15:52
I have the exact same issue on .NET Framework. Tried it on versions 4.8, 4.7.2 and 4.6.2 and it crashes with an access violation. \

It is very strange and it seems it has something to do with the name of the topic you are subscribing to. 3 and 11 character topic names work fine while for instance a 6 character topic name will induce the crash.

I'm hoping this will get looked into.

**Comment by jonny-binns** [comment] 2023-10-03 14:09
I also had the same issue with .NET 4.8, the fix for me was to roll back confluent.kafka and librdkafka.redist to 2.2.1. Then I cleaned and re-built my project and it worked. 

This isn't an optimal fix but if you need to get your app going this should work.

**Comment by anchitj** [comment] 2023-10-04 07:47
I tried reproducing with Dotnet SDK 6.0 and 7.0 on Ubuntu and Mac, but couldn't reproduce it. Will try checking with Dotnet Framework 4.8 on Windows machine.

**Comment by emasab** [comment] 2023-10-04 07:59
Hello, is this happening on a 32bit architecture? Seems similar to [this issue](https://github.com/confluentinc/librdkafka/issues/4398) that we've fixed recently with [this PR](https://github.com/confluentinc/librdkafka/issues/4398)

**Comment by MasoudKarimi92** [comment] 2023-10-04 08:04
> I tried reproducing with Dotnet SDK 6.0 and 7.0 on Ubuntu and Mac, but couldn't reproduce it. Will try checking with Dotnet Framework 4.8 on Windows machine.

I also had no problem using this package with .NET 6 or 7 on Windows machine. The problem only exists in .NET Framework.

**Comment by MasoudKarimi92** [comment] 2023-10-04 08:05
> Hello, is this happening on a 32bit architecture? Seems similar to [this issue](https://github.com/confluentinc/librdkafka/issues/4398) that we've fixed recently with [this PR](https://github.com/confluentinc/librdkafka/issues/4398)

No, I faced this issue on a 64bit architecture.

**Comment by anchitj** [comment] 2023-10-04 10:47
Thanks, I was able to reproduce this on Windows with dotnet framework 4.8. I think above PR by @emasab should fix the issue. I'll test it once we have the librdkafka 2.3.0 release done and will confirm here.

**Comment by alfhv** [comment] 2023-10-21 14:28
same issue on my side, all consumers migrated to v2.2.0 crash when executing line : 
https://github.com/confluentinc/confluent-kafka-dotnet/blob/v2.2.0/src/Confluent.Kafka/Impl/LibRdKafka.cs#L1044
(dotnet core 7, windows 64)

**Comment by anchitj** [comment] 2023-10-27 09:05
We have released 2.3.0. Can you test with that and confirm if the issue is there?

**Comment by alfhv** [comment] 2023-10-27 09:34
Fixed on my side

**Comment by fabmoll** [comment] 2023-10-27 10:00
Fixed here too :)
Thx !!

**Comment by anchitj** [comment] 2023-10-27 10:39
Thanks for confirming.

**Closed by anchitj** 2023-10-27 10:39 UTC
