### ISSUE TITLE
Sample usage OffsetForTimes

### ISSUE THREAD

**Issue by jake0029** [confluentinc/confluent-kafka-dotnet#981] opened 2019-06-14 03:44 UTC
Description
===========
OFFSET FOR TIMES

How to reproduce
================
Requesting sample code for consumer offsetfortimes under c# code, i haven't seen any of this for c sharp code..hoping you could help me with this. Thanks

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [0.11.6 ] Confluent.Kafka nuget version.
 - [2.0 ] Apache Kafka version.
 - [ ] Client configuration.
 - [Window Server 2008 R2 ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment] 2019-06-21 22:24
duplicate of #983

**Closed by mhowlett** 2019-06-21 22:24 UTC
