### ISSUE TITLE
Constant reprocessing of data when corrupted offset is stored in kafka

### ISSUE THREAD

**Issue by i5riza** [confluentinc/confluent-kafka-dotnet#1291] opened 2020-05-18 16:35 UTC
Description
===========

We identified strange some behavior of the client: every (every!) time the client is started/restarted, it consumes some partitions (not all) of the topic from zero offset to the very end.

Consumer is configured to auto commit every 5secs with manual store. Consumer group name is not changed, i.e. remains the same all the time.

How to reproduce
================

After doing some investigation, we identified that some partitions have invalid stored offset in kafka offset topic, i.e. stored offset is greater than max offset in partition. We also identified at least one way (there may be other ways to get the same result, since it does not fully explain our troubleshooting issue) to corrupt stored offset:

1. start consumer to work on some topic
2. delete and create topic while consumer is running (offset topic will be cleared from topic's offsets)
3. consumer will commit stored offset of previously known partition&offset

This will lead to committed offset value greater than offset available in recreated partition.

Inconsistency
================
We all understand why we have "corrupted" offset committed, but I am not sure if consumer behaves correctly while consuming all data from zero offset and does not commit.  Is that by design? 

What I expect from the client in this case is

a) fail, or
b) should not consume data with offset lower than committed one, or
c) should override previously committed offset with currently stored/processed one.

What i definitely do not expect is re-processing of all data every time consumer is connected.

I am also providing report for bad (left) and good (right) partitions (see attached image).

![offsets bad vs good](https://user-images.githubusercontent.com/1177757/82236292-8f54ac80-993c-11ea-94d5-76727bf16c6b.png)

What are your thoughts about that?

Checklist
=========
Kafka 2.4.1, 
Client 1.4 and 1.4.2

**Comment by mhowlett** [comment] 2020-05-18 17:19
the `AutoOffsetReset` config property controls behavior in the case of invalid (or unknown) offsets. Do you have this set to `Earliest`?

**Comment by i5riza** [comment] 2020-05-19 07:41
That's right, we have set value to Earliest intentionally, since we do not want to miss messages. 

BTW, saved "invalid" partition offset information will become valid right after source partition offset reaches 90603 (left part of previously attached image). After that, there will be no zero ground reprocessing after restart of consumer.

**Comment by mhowlett** [comment] 2020-05-19 13:21
if you set `AutoOffsetReset` to `Error`, it will fail in the case of invalid offsets. Note that the `AutoOffsetReset` config is only used in the case there are no committed offsets, or if the committed offsets are invalid.

Closing, since this is intended behavior.

**Closed by mhowlett** 2020-05-19 13:21 UTC

**Comment by i5riza** [comment] 2020-05-19 13:32
Unfortunately, consumer will fail (AutoOffsetReset:Error) in legal scenario when there are no corruptions, but new partition is added to the topic. This is dot desired behavior. Are there any options to fail on corrupted offset, but handle new partitions?

**Comment by mhowlett** [comment] 2020-05-19 13:44
Not automatic (adding partitions to a topic is not something that would generally happen as a matter of course). You could write logic to handle it using methods on the consumer (`Committed`). It may be good to differentiate not available / out of range scenarios, though that is a broader question (this client reflects behavior of clients in other languages).

**Comment by i5riza** [comment] 2020-05-19 14:00
Thank you for your insights! I agree, that differentiation of not available/out of range makes sense, since now client should be configured differently when consuming some topic for the first time (with Error it will not work), and successive starts.

**Comment by mhowlett** [comment] 2020-05-19 14:24
It may be the case that no-offset actually represents an error scenario in some cases, so assuming that means consume for the first time may be dangerous (I don't know any potential issues though without research).
