### ISSUE TITLE
Dotnet Kafka consumer using Kerberos and SSL on Windows

### ISSUE THREAD

**Issue by ghost** [confluentinc/confluent-kafka-dotnet#1727] opened 2021-11-22 18:28 UTC
Description
===========
I have a Kafka consumer in place and I'm trying to set up Kerberos and SSL for auth. This consumer is running on windows. I am not in control of the broker, only the client side. 
I'm running the program as the user that should be used for kerberos and the ACL should be set up on the other side. 

This is what my config looks like:

------------------------------------------------------------------------------
            var kafkaConfig = _configuration.GetSection("KafkaConsumerConfig");

            _bootstrapServers = kafkaConfig["BootstrapServers"];
            _topic = kafkaConfig["Topic"];

            var conf = new ConsumerConfig
            {
                GroupId = kafkaConfig["GroupId"],
                BootstrapServers = _bootstrapServers,
                AutoOffsetReset = AutoOffsetReset.Latest,
                StatisticsIntervalMs = 50000,
                EnableAutoCommit = true,
                SecurityProtocol = SecurityProtocol.SaslSsl,
                SslCaLocation = kafkaConfig["SslCaLocation"],
                SaslMechanism = SaslMechanism.Gssapi,
                SaslKerberosPrincipal = kafkaConfig["user"],
                SaslKerberosServiceName = "kafka",
                Debug = kafkaConfig["Debug"],
        
            };

------------------------------------------------------------------------------

This is the error that I keep getting: (I replaced the server name with xxxxxxxxxxxx for security)

Error: sasl_ssl://xxxxxxxxxxxx:9092/bootstrap: SSL handshake failed: SSL transport error: Unknown error (after 58ms in state CONNECT)

-----------------------------------------------------------------------------

Where do I go from here? Is this a problem with my ssl certs? Is my config missing something? How do I debug from here? 
Does "Error: sasl_ssl" mean that the issue could either be with the ssl OR Kerberos and its not specifying which one? 

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment] 2021-11-22 18:52
What client version are you on?

Please reproduce with `Debug = "broker,security,protocol"` and provide the logs.

**Comment by SalmaBelal** [comment] 2021-11-23 13:44
Im using Confluent.Kafka(1.4.4). 

Also I managed to fix the ssl issue but now I'm getting a different issue. I'll talk about it and show the logs for it lower down. 
But first, the way I fixed the ssl issue was providing port 39092 for the  BootstrapServers.  
"BootstrapServers": "xxxxxxxxxxx:39092,xxxxxxxxxxxx:39092,xxxxxxxxxxxx:39092". 
Initially I had "BootstrapServers": "xxxxxxxxxxx,xxxxxxxxxxxx,xxxxxxxxxxxx" and it was defaulting to port 9092. 
(I replaced the server name with xxxxxxxxxxxx for security)

I assume this is broker/implementation specific and not something that needed for every sasl_ssl Kerberos implementation. Please correct me if that assumption is wrong. 

Now, I'm getting a different problem though. 
Seems like a problem with Kerberos authentication. This is what I have in place so far....I'm running the client as the user I wish to use, I have the SaslKerberosPrincipal field set for this user, and the ACL should be configured on the other side (ACL uses a combination of the user and the GroupId). So is this issue most likely related to something going wrong with these three items? Or am I possibly missing a config/setting? For example, I've seen that Java makes use of a krb5.conf file. Is that something I need to use for dotnet? Is there anything else similar to this that I might be missing?

Below are the logs...again I replaced the server name with xxxxxxxxxxxx for security.
--------------------------------------------------------------------------------------
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Broker SSL certificate verified
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Connected (#5)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Broker changed state CONNECT -> APIVERSION_QUERY
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Sent ApiVersionRequest (v3, 52 bytes @ 0, CorrId 13)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Received ApiVersionResponse (v3, 344 bytes, CorrId 13, rtt 31.01ms)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Auth in state APIVERSION_QUERY (handshake supported)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Broker changed state APIVERSION_QUERY -> AUTH_HANDSHAKE
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Sent SaslHandshakeRequest (v1, 29 bytes @ 0, CorrId 14)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Received SaslHandshakeResponse (v1, 14 bytes, CorrId 14, rtt 27.39ms)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Broker supported SASL mechanisms: GSSAPI
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Auth in state AUTH_HANDSHAKE (handshake supported)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Broker changed state AUTH_HANDSHAKE -> AUTH_REQ
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Initializing SASL client: service name kafka, hostname xxxxxxxxxxxx , mechanisms GSSAPI, provider Win32 SSPI
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Acquired Kerberos credentials handle (expiry in 2147483404.-322922497s)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Send SASL Kafka frame to broker (1863 bytes)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Sent SaslAuthenticateRequest (v0, 1888 bytes @ 0, CorrId 15)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Received SaslAuthenticateResponse (v0, 105 bytes, CorrId 15, rtt 36.88ms)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: failed: err: Local: Authentication failure: (errno: No error)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Broker changed state AUTH_REQ -> DOWN
Error: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: SASL authentication error: Authentication failed during authentication due to invalid credentials with SASL mechanism GSSAPI (after 44ms in state AUTH_REQ)
Debug, [thrd:sasl_ssl://xxxxxxxxxxxx :39092/bootstrap]: sasl_ssl://xxxxxxxxxxxx :39092/bootstrap: Broker changed state DOWN -> INIT

------------------------------------------------------------------------------------

Thank you for your support!

**Comment by mhowlett** [comment] 2022-10-10 17:19
i'm currently going through triaging issues. going to close this as likely not an issue with the client (except for the potential maybe for better logging). sorry i don't have the bandwidth to dig in.

**Closed by mhowlett** 2022-10-10 17:19 UTC
