### ISSUE TITLE
error creating topic

### ISSUE THREAD

**Issue by robsonrjan** [confluentinc/confluent-kafka-dotnet#1367] opened 2020-07-31 07:50 UTC
Description
===========

.....Exceptions.StreamingBusException
  HResult=0x80131500
  Message=KafkaClient ERROR: Broker: Unknown topic or partition
  Source=KafkaClient
  StackTrace:
   at ....KafkaClient.KafkaListener.Listen() in C:\GIT\...\KafkaListener.cs:line 134
   at ....KafkaClient.KafkaListener.<ListenAsync>b__12_0() in C:\GIT\...\KafkaClient\KafkaListener.cs:line 91
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

  This exception was originally thrown at this call stack:
    [External Code]
    ....KafkaClient.KafkaListener.Listen() in KafkaListener.cs

Inner Exception 1:
ConsumeException: Broker: Unknown topic or partition

How to reproduce
================

Acks = Acks.None,
GroupId = configuration.ConsumerGroup ?? DefaultConsumerGroup,
EnableAutoCommit = true,
FetchWaitMaxMs = FetchWaitMaxMs,
AutoCommitIntervalMs = 4000,
StatisticsIntervalMs = 60000,
AutoOffsetReset = AutoOffsetReset.Earliest,
AllowAutoCreateTopics = true,
ApiVersionRequest = false and true

consumer.Subscribe(someTopic);

result = consumer.Consume(cancelToken.Token);

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. - 1.5.0
 - [x] Apache Kafka version. - 5.3.1
 - [x] Client configuration.
 - [x] Operating system. kubernetes
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by mhowlett** [comment] 2020-07-31 13:25
afaict this is a duplicate of #1366

**Closed by mhowlett** 2020-07-31 13:25 UTC
