### ISSUE TITLE
Error "no OPENSSL_AppLink" when trying to configure SSL in .Net producer

### ISSUE THREAD

**Issue by rangercej** [confluentinc/confluent-kafka-dotnet#1708] opened 2021-10-25 13:21 UTC
Description
===========
_Following some more poking, this appears to be a regression with 1.8.0. I've gone to Confluent.Kafka 1.6.3 and 1.7.0 and the same code works without changes and I can push messages. As soon as I push to 1.8.0, I get the "no OPENSSL_AppLink" error, which remains through 1.8.1 and 1.8.2. Original report follows:_

I am trying to write a piece of C# that can authenticate with a client certificate to a test kafka instance. On running the code, I get the following error when calling `ProducerBuilder()`, and the code immediately terminates (doesn't even throw an exception):

    OPENSSL_Uplink(00007FF9C9C78D30,08): no OPENSSL_Applink

No errors or messages appear in the Kafka server logs.

If I comment out the lines that set the certificate (i.e., remove the config for SslKeystoreLocation and both passwords), then the error doesn't occur (but I don't authenticate either as the Kafka server is configured for mutual authentication), and I do see an "Failed authentication with /10.168.84.10 (SSL handshake failed)" error message in the Kafka logs, so the server is reachable.

Client machine is Windows 10 20H2, C# code is built against .Net Core 3.1.
Confluent.Kafka version 1.8.2
Server machine is Linux (Ubuntu 21.04) running Kafka 2.13

C# code:
[Program.txt](https://github.com/confluentinc/confluent-kafka-dotnet/files/7410314/Program.txt)

How to reproduce
================
Execute the code in the attachment (having configured BootstrapServers and a suitable PKCS#12 certificate and password) against a Kafka configured for TLS authentication.

Checklist
=========

Please provide the following information:
 - [X] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [X] Apache Kafka version.
 - [X] Client configuration.
 - [X] Operating system.
 - [X] Provide logs (with "debug" : "..." as necessary in configuration).
 - [X] Provide broker log excerpts. **[Reporter note -- There are no log entries created server-side, so no log included]**

**Comment by Purvesh-shah** [comment] 2021-12-03 16:41
Any update on this ?
We are also facing same issue 

using .net framework 4.7 using VStudio 2015, we are using confluent.kafka 1.5.3 and we upgraded to 1.8.2  we are getting OPENSSL_Uplink no OPENSSL_Applink issue 

We downgrade to 1.7.0  and it started working

**Comment by andreiaugustin** [comment] 2021-12-21 11:09
no OPENSSL_Applink is a documented problem in OpenSSL's [FAQ](https://www.openssl.org/docs/faq.html) at " I’ve compiled a program under Windows and it crashes: why? ", essentially you have to compile in the applink.c.

**Comment by mhowlett** [comment] 2022-04-20 21:00
i just uploaded v1.9.0-RCb to nuget - can you check if this is resolved?

**Comment by CREFaulk** [comment] 2022-04-27 14:43
> i just uploaded v1.9.0-RC2b to nuget - can you check if this is resolved?

It's a package used in a shared package here. I'm talking with the devs to get it tested. Thanks!

**Comment by CREFaulk** [comment] 2022-04-29 16:59
Now I get a different error
`Exception has occurred: CLR/System.InvalidOperationException
Exception thrown: 'System.InvalidOperationException' in Confluent.Kafka.dll: 'Error reading ssl.keystore.location PKCS#12 file: [snipped]/kafka/tls/client/kafka.client.keystore.jks: error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data'
   at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config, IClient owner)
   at Confluent.Kafka.Consumer`2..ctor(ConsumerBuilder`2 builder)
   at Confluent.Kafka.ConsumerBuilder`2.Build()`

**Comment by mhowlett** [comment] 2022-05-02 14:09
> /kafka/tls/client/kafka.client.keystore.jks

looks like you're trying to use .jks file (a java format).

i wrote some notes on setting this stuff up a while ago which might help (can't recall if they specifically address your problem or not).

**Comment by mhowlett** [comment] 2022-05-02 14:09
https://github.com/mhowlett/confluent-kafka-dotnet/tree/security/examples/Security

**Comment by EnocAnanda** [comment] 2022-06-09 16:56
> Now I get a different error. I might not have a good way to test without taking too much time away from my work tasks. The original issue only seems to affect consumers and not when just publishers were used.
> 
> `Exception has occurred: CLR/System.InvalidOperationException Exception thrown: 'System.InvalidOperationException' in Confluent.Kafka.dll: 'Error reading ssl.keystore.location PKCS#12 file: [snipped]/kafka/tls/client/kafka.client.keystore.jks: error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data' at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config, IClient owner) at Confluent.Kafka.Consumer`2..ctor(ConsumerBuilder`2 builder) at Confluent.Kafka.ConsumerBuilder`2.Build()`

I also see the same error when I attempt to use the pre-release RC's for v1.9.x, whether I include the dependent library as an external package or not. At this point with the C# .NET Client, we have to use v1.7.0 of the Confluent NuGet packages. Nothing above that level works for us. Yes, we are using the keystore approach and we have to for mTLS support.

**Comment by pfjason-bbmus** [comment] 2022-06-21 21:25
We're also stuck on Confluent.Kafka 1.7.0 with a not enough data error in 1.9.0 and various other errors with the 1.8.x versions. If it helps our private keys are are Elliptic Curve and not RSA, so they are much smaller than if you're testing for RSA keysizes.

```
error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data
   at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config, IClient owner)
```

**Comment by Leszek-Kowalski** [comment] 2022-07-08 10:03
> We're also stuck on Confluent.Kafka 1.7.0 with a not enough data error in 1.9.0 and various other errors with the 1.8.x versions. If it helps our private keys are are Elliptic Curve and not RSA, so they are much smaller than if you're testing for RSA keysizes, and our keystores are PKCS#12 files.
> 
> ```
> error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data
>    at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config, IClient owner)
> ```

We are experiencing the very same error message on 1.9.0 with RSA private keys PKCS#12 certificates. Also stuck on 1.7 which in turn has a cross platform incompatibility with Java when using protobuf.
@mhowlett this situation is a blocker for our PoC project - is this bug on your backlog ?

**Comment by RedTail72** [comment] 2022-08-08 11:51
> We're also stuck on Confluent.Kafka 1.7.0 with a not enough data error in 1.9.0 and various other errors with the 1.8.x versions. If it helps our private keys are are Elliptic Curve and not RSA, so they are much smaller than if you're testing for RSA keysizes, and our keystores are PKCS#12 files.
> 
> ```
> error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data
>    at Confluent.Kafka.Impl.SafeKafkaHandle.Create(RdKafkaType type, IntPtr config, IClient owner)
> ```

I can confirm this is also occurring in 1.9.2 with RSA keys.  Reverting back to 1.7 resolves the issue for me as well.

**Comment by pfjason-bbmus** [comment] 2022-08-10 15:15
As an update this appears to be an underlying openssl issue. We were able to work around this by changing from using a pks keystore file for the credential to separate certificate and key files.

**Comment by deuko** [comment] 2022-08-16 07:50
We have the same issue, config works in 1.7.0 but gives `error:0D06B08E:asn1 encoding routines:asn1_d2i_read_bio:not enough data` in 1.9.2

Config when connecting:
`SecurityProtocol = SecurityProtocol.Ssl,
 SslKeystoreLocation = <path to pksc12 file containing keys>,
 SslKeystorePassword = <pw>,
 SslKeyPassword = <pw>,
 SslCaLocation = <path to cert file containing root ca>`

Initially I also only got a java keystore (jks) file which didnt work, but converted it to pkcs12 and extracted root-ca certs which works for 1.7.0 only

**Comment by MichalBrylka** [comment] 2022-08-19 09:44
@deuko which commands (like openssl CLI) are you using to extract root CA certs to a file ?

**Comment by deuko** [comment] 2022-08-19 10:44
@MichalBrylka I used the following commands:

First convert jks to pkcs12
`keytool.exe -importkeystore -srckeystore keystore.jks -srcstoretype JKS -deststoretype PKCS12 -destkeystore keystore.p12`

Extract ca / cert
`openssl pkcs12 -in keystore.p12 -nokeys -out certs.crt`

The config value SslCaLocation points to certs.crt

**Comment by MichalBrylka** [comment] 2022-08-19 11:09
@deuko 
thanks, we did the same. Sadly it did not work. Apparently we are using some old and weak ciphers. Anybody knows how can we convince Confluent.Kafka to use legacy OpenSSL provider ? Kinda like in CLI:
openssl.exe -legacy 
?

**Comment by mhowlett** [comment] 2022-10-12 14:57
the "asn1_d2i_read_bio:not enough data" issue, assuming you're on windows, is resolved here: https://github.com/edenhill/librdkafka/issues/3992 (will be in next release).

**Comment by mhowlett** [comment] 2022-10-12 14:59
the reported issue is resolved here: https://github.com/edenhill/librdkafka/pull/3602

**Closed by mhowlett** 2022-10-12 14:59 UTC
Labels: bug, librdkafka
