### ISSUE TITLE
librdkafka segfault when topic == null

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#864] opened 2019-04-03 22:12 UTC
`rd_kafka_topic_partition_list_add` segfaults when the topic parameter value is NULL. this is appropriate behavior in C but in C# we should never segfault. Instead, we should throw a `NullPointerException`. To achieve this we'll need to validate the parameters of `GetCTopicPartitionList`.

This is also very likely an issue in other places in the code. We should audit the entire API for this problem and fix.

**Comment by callenWrench** [comment] 2019-10-06 07:13
When we make this check (for null topic), is there any reason we shouldn't also check for an all-whitespace string? At least on non-critical performance paths.

**Comment by PSanetra** [comment] 2021-01-13 10:39
@mhowlett This issue still exists for the Methode `SafeKafkaHandle.Subscribe`

**Comment by mhowlett** [comment] 2021-01-13 17:31
thanks @PSanetra - this was resolved by https://github.com/confluentinc/confluent-kafka-dotnet/pull/1463 which is in the 1.6.x branch.

**Comment by pranavrth** [comment] 2024-06-18 12:29
The issue is fixed. Closing the issue.

**Closed by pranavrth** 2024-06-18 12:29 UTC
Labels: bug
