### ISSUE TITLE
Assert hit in round robin assignor

### ISSUE THREAD

**Issue by mhowlett** [confluentinc/confluent-kafka-dotnet#1369] opened 2020-08-04 15:47 UTC
via: @wwarby https://github.com/confluentinc/confluent-kafka-dotnet/issues/1366#issuecomment-668669487

I've just run into massive instability after upgrading some high throughput C# apps from v 1.4.4 to 1.5.0. In my case the error thrown is

dotnet: rdkafka_roundrobin_assignor.c:97: rd_kafka_roundrobin_assignor_assign_cb: Assertion `next < rd_list_cnt(&eligible_topic-> members)' failed

... and results in an all out application crash. Rolled back to 1.4.4 and it solved the problem.

In my case, I'm consuming data from topics that already exist and I don't have topic auto-creation enabled - I'm running multiple instances of the C# app, each instantiating a single consumer to join the consumer group.

**Comment by mhowlett** [comment] 2020-08-04 15:49
cc: @edenhill

**Comment by ralmsdeveloper** [comment] 2020-08-10 19:28
Hello @mhowlett,
Will we have a patch for this?
I have the same problems.

**Comment by mhowlett** [comment] 2020-08-10 21:57
magnus is currently out of the office - he was making changes to this, so i'll let him investigate when he gets back. For now, revert to 1.4.4.

**Comment by ralmsdeveloper** [comment] 2020-08-10 22:05
Yes, it worked for me!
I will try to find the reason for the bug, I will be happy to contribute!

**Comment by mhowlett** [comment] 2020-08-11 13:49
thanks! suggest looking at librdkafka PRs since 1.4.4 that touch the round robin code.

**Comment by mhowlett** [comment] 2020-08-13 03:07
additionally: https://github.com/confluentinc/confluent-kafka-dotnet/issues/1366#issuecomment-673198582

> upon calling consume the first time, it throws an exception, but if you try the second time it works

**Comment by wwarby** [comment] 2020-12-04 07:07
Any ETA on a fix for this?

**Comment by edenhill** [comment] 2020-12-04 07:30
We'll hopefully release v1.5.3 today or early monday.

**Comment by plachor** [comment] 2020-12-07 10:14
pre-release or stable ?

**Comment by plachor** [comment] 2020-12-08 06:28
@mhowlett will you pre-release v1.5.3-RC5 ? I'm looking for checking if my issues are gone after update.

**Comment by mhowlett** [comment] 2020-12-08 14:29
#1473

**Comment by mhowlett** [comment] 2020-12-08 16:13
https://www.nuget.org/packages/Confluent.Kafka/1.5.3-RC5

**Comment by plachor** [comment] 2020-12-09 11:32
@mhowlett, @edenhill  seems that my issues with endless loop in round-robin assignor are gone. Also my tests are green. 

Once you release stable version I will check if round-robin is distributing partitions properly among existing members in case of uneven subscriptions for topics with non-const partitions count. Any ETA for stable release ?

**Comment by edenhill** [comment] 2020-12-09 11:57
librdkafka v1.5.3 is out, dotnet client should be out later today.

**Comment by plachor** [comment] 2020-12-09 12:01
Great thnx

**Comment by plachor** [comment] 2020-12-11 07:28
Round-robin assignor is now working as intended :)

**Closed** 2024-05-28 12:34 UTC
Labels: bug, librdkafka
