### ISSUE TITLE
System Null Reference Exception while using a simple consumer

### ISSUE THREAD

**Issue by chiru1205** [confluentinc/confluent-kafka-dotnet#220] opened 2017-06-08 20:39 UTC
While testing out a consumer locally. I keep getting System.NullReferenceException

Exception: System.NullReferenceException Message: Object reference not set to an instance of an object. StackTrace: at Confluent.Kafka.Internal.Util.Marshal.PtrToStringUTF8(IntPtr strPtr) at Confluent.Kafka.Impl.SafeKafkaHandle.get_MemberId() at Confluent.Kafka.Consumer`2.get_MemberId() at Test.Monitor.<>c.<Start>b__28_4(Object obj, List`1 partitions) at Confluent.Kafka.Impl.LibRdKafka.NativeMethods.rd_kafka_destroy(IntPtr rk) at Confluent.Kafka.Impl.SafeKafkaHandle.ReleaseHandle() at System.Runtime.InteropServices.SafeHandle.InternalFinalize() at System.Runtime.InteropServices.SafeHandle.Dispose(Boolean disposing) at System.Runtime.InteropServices.SafeHandle.Finalize()

Error is occuring on OnParititionsRevoked even. At this point consumer.memberID is basically null.
![image](https://user-images.githubusercontent.com/16243876/26949519-e45b6d4a-4c5f-11e7-82d9-c252da6f38e0.png)

Not sure what  could be causing this. Here is my memory usage
![image](https://user-images.githubusercontent.com/16243876/26949560-06010392-4c60-11e7-9d83-f8d616f9e556.png)

Here is my consumer code at this moment

 _kafkaConsumer = new Consumer<Null, string>(consumerConfig, null,
                new StringDeserializer(System.Text.Encoding.UTF8));           

                _kafkaConsumer.OnMessage += (_, msg) =>
                {
                    lock (Lock)
                    {
                        LatestProcessedMessageOffset = msg.Offset;
                    }
                    ProcessMessage(msg);
                };

               _kafkaConsumer.OnError += (_, error) =>
                {
                                    Logger.Error($"Error [{error}], Consumer{_kafkaConsumer.MemberId} on Server {Environment.MachineName}");
                };

                _kafkaConsumer.OnPartitionsAssigned += (obj, partitions) =>
                {
                    var fromBeginning = partitions.Select(p => new TopicPartitionOffset(p.Topic, p.Partition,Offset.Beginning)).ToList();
                    _kafkaConsumer.Assign(fromBeginning);
                    Logger.Info($"Assigned partitions: [{string.Join(", ", partitions)}], Assigned to the Consumer{_kafkaConsumer.MemberId} on Server {Environment.MachineName}");

                };

                _kafkaConsumer.OnPartitionsRevoked += (obj, partitions) =>
                {
                    _kafkaConsumer.Unassign();
                     Logger.Error($"Revoked partitions: [{string.Join(", ", partitions)}], Consumer{_kafkaConsumer.MemberId} on Server {Environment.MachineName}");
                };

                _kafkaConsumer.OnConsumeError += (_, msg) =>
                {
                    //TODO: need to restart consumer subscription
                    Logger.Error($"Error consuming from topic/partition/offset {msg.Topic}/{msg.Partition}/{msg.Offset}: {msg.Error},Consumer{_kafkaConsumer.MemberId} on Server {Environment.MachineName}");

                };

                _kafkaConsumer.Subscribe(config.Current.TARS.KafkaTopic_TestAttempt);
                
                while (true)
                {
                              _kafkaConsumer.Poll(TimeSpan.FromMilliseconds(100));
                }

Seems like Consumer is disposed from memory? Not sure how that happened

**Comment by chiru1205** [comment] 2017-06-08 20:41
There is a registered event in the EventViewer. worker process gave up and app pool restarted automatically

![image](https://user-images.githubusercontent.com/16243876/26949800-ecabdfec-4c60-11e7-88dc-198311843886.png)

**Comment by treziac** [comment] 2017-06-09 16:27
Indeed there is a bug, we compare to null instead of IntPtr.Zero when converting MemberId

I don't know why you have a null memberId and dispose the safehandle though - more important bug. Can you try removing this MemberId  in your strings and see what happens?
Do you have any way to reproduce? (os, version, exact code, how many consumer you launch...)

Thanks!

**Comment by chiru1205** [comment] 2017-06-09 19:04
Its a single consumer instance per each server(on which my app is running). We currently have two app servers so 2 consumer instances running. Seen this error in the event viewer of all severs. First I noticed this issue locally while doing some speed test. 

1 Windows 7 (64 bit)
2. .NET 4.6.1
3. One kafka broker(running on my windows machine)

I did not notice this issue before. I have recently added logging on all the event handlers. I have noticed that OnPartitionedRevoked event is kind of stuck in an infinite loop or something because I keep getting call backs on that specific event because my logging statement has consumer.memberId(which was some how became null) is blowing up.

I'll test by removing memberId and see what happens. 

> I don't know why you have a null memberId and dispose the safehandle though - more important bug
I really don't know how this happened. I have not disposed my consumer instance explicitly it runs in an infinite loop. My consumer code is posted in my first comment. its plain and simple.

Here are my configuration parameters

 private static Dictionary<string, object> GetConsumerConfig(string groupId, string brokerList, bool enableAutoCommit) =>
            new Dictionary<string, object>
            {
                { "group.id", groupId },
                { "enable.auto.commit", enableAutoCommit },
                { "auto.commit.interval.ms", 5000 },
                { "statistics.interval.ms", 60000 },
                { "bootstrap.servers", brokerList },
                { "default.topic.config", new Dictionary<string, object>()
                    {
                        { "auto.offset.reset", "smallest" }
                    }
                }
            };

**Comment by treziac** [comment] 2017-06-09 19:47
Thanks for feeback!

I wonder if it's not a problem in the pdb with unsafe code wrongly pointing the stack to releaseHandle - I think you indeed have a null memberId when partition are revoked due to coordintor mechanism (will have to check on librdkafka). You should be able to call MemberId before the Unassign, and the bug when calling it after Unassign will be fixed in #222 (but indeed, it's a problematic bug).

Also, why do you log the PartitionRevoked as an error? This is a normal behaviour - kafka mechanism with coordinator is to unsubscribe to all partition and reassign. If you have one consumer started and start a second one, the first one will receive a PartitionRevoked, then PartitionAssigned

**Comment by chiru1205** [comment] 2017-06-09 20:03
@treziac . I have added logging to monitor whats going on behind the scenes. Its just a log in my case . I'll make that informational. I'll move the code of line and put it before I do the unassign call.

**Comment by mhowlett** [comment] 2018-08-14 21:11
closing as #222 was merged. it's not clear to me if other discussion in this thread represents a problem with the library or it's use. Since this issue was reported we've changed some things that may be relevant - added object disposed checking to `kafkaHandle` methods (including `MemberId`) and fixed some issues with finalization. please open a new issue and reference this one if problems persist.

**Closed by mhowlett** 2018-08-14 21:11 UTC
