### ISSUE TITLE
The type initializer for 'Confluent.Kafka.Impl.LibRdKafka' threw an exception

### ISSUE THREAD

**Issue by MSDRIOUICH** [confluentinc/confluent-kafka-dotnet#77] opened 2017-02-24 15:13 UTC
Hello,
I am using the liberary in my Windows Service VS2015 solution, and its work fine on my devlopement environment under Windows 7 Entreprise .
However, when I install the service ( InstallUtil.exe -i myService.exe, with the same binaries) on my testing server (Windows Server 2008 R2, Framework .net 4.5.2), I get the following error when trying:
"The type initializer for 'Confluent.Kafka.Impl.LibRdKafka' threw an exception"

I used 0.9.2.0
I am now using the 0.9.4-preview8, I got same probleme.

Thank you in advance for any suggestions?

**Comment by mhowlett** [comment] 2017-02-24 15:25
this is being tracked in #76

**Comment by ewencp** [comment] 2017-02-27 02:07
Closing as duplicate of #76.

**Closed by ewencp** 2017-02-27 02:07 UTC
