### ISSUE TITLE
How do I send messages quickly without getting memory access exceptions

### ISSUE THREAD

**Issue by JWroe** [confluentinc/confluent-kafka-dotnet#50] opened 2017-02-15 22:44 UTC
Hi, as per the title. This might be a stupid question but I can't figure out how to do this without writing some arbitrary throttling code. Using the simple code below:
```
using (var producerConnection = new Producer<Null, string>(config.ProducerConfig, null, new StringSerializer(Encoding.UTF8)))
            {
                while (true)
                {
                    Console.WriteLine("Enter the number of messages to publish...");
                    if (int.TryParse(Console.ReadLine(), out int num))
                    {
                        for (var i = 0; i < num; i++)
                        {
                            producerConnection.ProduceAsync("my-topic", null, $"Message #{i}");
                        }
                        producerConnection.Flush();
                    }
                }
            }
        }
```
This works great for small numbers but if I try say 50,000 messages I get the following error
> System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

If I add a `.Wait()` to the end of my `ProduceAsync()` call this kills the performance. I also tried flushing after every N messages but that seemed to give me the worst of both worlds. 

Thanks for the help.

**Comment by mhowlett** [comment] 2017-02-15 23:15
Are you referencing the 0.9.2-preview package on nuget? unfortunately there is a bug in that version which would cause this behavior. this is fixed in master (which to my knowledge is now stable, though we haven't finished testing yet).

**Comment by mhowlett** [comment] 2017-02-15 23:24
I will push a new version to nuget shortly.

**Comment by mhowlett** [comment] 2017-02-16 00:59
there is now a 0.9.4-preview2 package on nuget.org. If this does not resolve the problem, please reply and i'll try to reproduce.

**Comment by JWroe** [comment] 2017-02-16 07:23
Fantastic updating has fixed it, cheers for the quick help!

**Comment by GoodGuyJim** [comment] 2017-03-29 13:20
@mhowlett hey sorry for posting in a closed issue but I am having the same problem and figured it would be better to put my comment in this thread (if you'd prefer I could make a new issue).

I am currently working on replacing RdKafka with Confluent Kafka, and if I don't do something to throttle the producer messages I will get the same System.AccessViolationException as detailed in this thread. I am working with the most recent version of Confluent Kafka and librdkafka.

At the moment I am working on using the features of the package to handle retries and fiddling with some settings in order to get it to work, it's possible something I am doing is causing this, so here are the settings I currently have on my Producers.

**Topic configs**
request.required.acks = -1
message.timeout.ms = 5000

**Global configs**
bootstrap.servers = settings.BrokerPath
max.in.flight.requests.per.connection = 1
message.max.bytes = 500000000
retries = 10000000

Here's the full stack trace of the error I see in the Event Log.

```
Application: ServiceWrapper.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.AccessViolationException
   at Confluent.Kafka.Impl.LibRdKafka+NativeMethods.rd_kafka_message_timestamp(IntPtr, IntPtr ByRef)
   at Confluent.Kafka.Impl.LibRdKafka.message_timestamp(IntPtr, IntPtr ByRef)
   at Confluent.Kafka.Producer.DeliveryReportCallbackImpl(IntPtr, IntPtr, IntPtr)
   at Confluent.Kafka.Impl.LibRdKafka+NativeMethods.rd_kafka_poll(IntPtr, IntPtr)
   at Confluent.Kafka.Impl.LibRdKafka.poll(IntPtr, IntPtr)
   at Confluent.Kafka.Producer+<>c__DisplayClass9_0.<StartPollTask>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.LongRunningThreadWork(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```
   
Any help or insight you could provide would be greatly appreciated, thanks!

**Comment by mhowlett** [comment] 2017-03-29 17:00
Labelling this as bug if only because we should not ever be throwing`AccessViolationException`s.

are you setting `api.version.request`? what broker version are you using?

If you post minimal complete example demonstrating the problem, that is the quickest way for us to investigate.

**Comment by edenhill** [comment] 2017-03-29 17:33
It looks like you are trying to get the timestamp for a produced message (on the producer).
Message timestamps are not currently supported in the delivery report callbacks.

**Comment by GoodGuyJim** [comment] 2017-03-29 17:43
@mhowlett No I am not, I just read what that does, should I be setting that to 0.9.4?

As far as I can tell I'm not doing anything special. I'm using F# so I hope this makes sense to you (the logging stuff is an internal thing)

```
let deliveryReport = producer.ProduceAsync(topic, null, message)

let contWith (task:Task<Message>) =           
  match task.Result.Error.Code with
  | ErrorCode.NoError -> LogToCore logger LogLevel.Info (sprintf "Produced message to topic %s successfully" topic) None []
  | error             -> LogToCore logger LogLevel.Warn "Producing Attempt failed." None [("Error Code", error.ToString())]

deliveryReport.ContinueWith(Action<Task<Message>> contWith) |> ignore
```

@edenhill interesting, I am not explicitly trying to get the timestamp anywhere, could this be happening as a side effect of something else?

**Comment by mhowlett** [comment] 2017-03-29 18:25
yeah, the timestamp is marshaled from librdkafka regardless of whether it is used. I think @edenhill noticed the error message is related to timestamps and recalled that delivery report timestamps are broken in the current released nuget package (they are fixed in master now). My first instinct of what to try are things related to versioning. try setting `api.version.request` to `true`. also what broker version are you using?

**Comment by mhowlett** [comment] 2017-03-29 18:27
Also try calling `Library.VersionString` to verify the version of librdkafka being found. If it's not 0.9.4, that's the problem. We've seen the wrong version being found in some scenarios where people have installed librdkafka other ways.

**Comment by GoodGuyJim** [comment] 2017-03-29 20:00
We're using 3.1.1, Library.Version string prints 0.9.4 at runtime.

After setting `api.version.request` everything seems to be working! Sorry if I missed that in the docs, is there anything else you'd like me to try out?

**Comment by edenhill** [comment] 2017-03-29 20:45
Weird, I don't really see how api.version.request could cause a crash in the delivery report handler.

**Comment by wojciechrak** [comment] 2017-08-04 11:40
Hi there,
I am not sure if this is the same issue, but it is memory related too.

When exetuing this little program, memory usage for this process jumps to ~20GB (my system has 16GB ram)
Sometimes it even makes my os (Win10) unstable, screen goes dark, other program crash etc.

````
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Confluent.Kafka;
using Newtonsoft.Json;

namespace KafkaProducerTest
{
    class Program
    {
        private const int N = 100_000;

        static void Main(string[] args)
        {
            Console.WriteLine($"lib version: {Library.VersionString}");
            Console.WriteLine("Press <Enter> to start...");
            Console.ReadLine();

            var topic = "test";
            var cfg = new Dictionary<string, object>{
                {"bootstrap.servers", "kafka:9092"},
                {"queue.buffering.max.ms", 100},
                {"client.id" , "test-client"},
                {"message.max.bytes" , 10240},
                {"batch.num.messages", 1000},
                {"request.required.acks", (int)AcksEnum.WaitForAckFromLeader},
                {"api.version.request", true}
            };

            Console.WriteLine(JsonConvert.SerializeObject(cfg, Formatting.Indented));

            using (var producer = new Producer(cfg))
            {
                var payload = new byte[8192];
                Task.WhenAll(Enumerable.Range(0, N).Select(x => producer.ProduceAsync(topic, null, payload))).Wait();
            }
        }
    }
}

````

Strangely enough, increasing `message.max.bytes` to `102400` makes it work fine.

**Comment by treziac** [comment] 2017-08-07 15:25
@wojciechrak 
While testing, I spotted a bug on librdkafka, see here:
https://github.com/edenhill/librdkafka/issues/1363

Note that when I test your code on my computer (either local or remote zookeeper/kafka), I have no issue (6GB used)

Couple of things here:
- batch are limited by message.max.bytes, so your limit here is one. Can you try setting `batch.num.messages` to 1 to see if you have some improvements (for tracking of the librdkafka issue mentioned at start)
- You should use the ProduceAsync which takes an IDeliveryHandler, not the one which return a task
 When you use the tasked produceAsync, it will create a completion task on every call - so one for the 100_000 objects you send, which will also contain a copy of the data. The task one should be used when you actually await for one (or say a small number) ack(s) of specific messages. In your example, you would rather do this

```
using System;
using System.Collections.Generic;
using Confluent.Kafka;
using Newtonsoft.Json;
using System.Threading;

namespace KafkaProducerTest
{
    class Program
    {
        private const int N = 100_000;

        static void Main(string[] args)
        {
            Console.WriteLine($"lib version: {Library.VersionString}");
            Console.WriteLine("Press <Enter> to start...");
            Console.ReadLine();

            var topic = "test";
            var cfg = new Dictionary<string, object>{
                {"bootstrap.servers", "kafka:9092"},
                {"queue.buffering.max.ms", 100},
                {"client.id" , "test-client"},
                {"message.max.bytes" , 10240},
                {"batch.num.messages", 1000},
                {"request.required.acks", 0},
                {"api.version.request", true},
            };

            Console.WriteLine(JsonConvert.SerializeObject(cfg, Formatting.Indented));



            using (var producer = new Producer(cfg))
            {
                var dh = new DeliveryHandler(N);
                var payload = new byte[8192];
                for (int i = 0; i < N; i++)
                {
                    producer.ProduceAsync(topic, null, payload, dh);
                }
                dh.AutoEvent.WaitOne();
            }
            Console.WriteLine("Press <Enter> to quit...");
            Console.ReadLine();
        }
    }

    public class DeliveryHandler : IDeliveryHandler
    {
        public int NumberOfMessages { get; private set; }
        public AutoResetEvent AutoEvent { get; private set; }

        public DeliveryHandler(int numberOfMessages)
        {
            NumberOfMessages = numberOfMessages;
            AutoEvent = new AutoResetEvent(false);
        }

        public bool MarshalData { get { return false; } }

        public void HandleDeliveryReport(Message deliveryReport)
        {
            if (--NumberOfMessages == 0)
            {
                AutoEvent.Set();
            }
            if(deliveryReport.Error.HasError)
            {
                //handle error here, message was not acked, details in deliveryReport.Error
            }
        }
    }
}
```
You will see an impact on both RAM used and GarbageCollection.

- for note, `queue.buffering.max.kbytes` is by default 4_000_000, meaning you can queue up to 4GB of data (+ all override of confluent.Kafka like copy of data for tasked ProduceAsync). You can lower this if you are limited on RAM, and ProduceAsync will block until there is some space. You can also instruct ProduceAsync to throw if queue is full via one of its overload (blockIfQUeueFull)

**Comment by mhowlett** [comment] 2018-08-24 22:11
I'm closing this since the relevant implementation has changed considerably since this issue was filed (including considerable effort to avoid access violation exceptions). Please open a new issue if this problem is encountered in a 1.0 pre-release version or higher.

**Closed by mhowlett** 2018-08-24 22:11 UTC
Labels: bug
