### ISSUE TITLE
Authorization error from windows client when using DNS A record DNS instead of broker hostname using SASL_PLAINTEXT 

### ISSUE THREAD

**Issue by sysThematic** [confluentinc/confluent-kafka-dotnet#1319] opened 2020-06-10 09:13 UTC
Description
===========
We've a kafka cluster running on linux hosts. Configured with SASL_PLAINTEXT. Both linux hosts and windows are on the same Active Directory Domain.

We have Confluent Open Source version 5.3.0, Apache version equiv. 2.3.0 running on Redhat hosts.

As told with issue #2549 we want to use a librdkafka's round robin DNS support and use a DNS record rather than broker's hostname.
When I use kafkacat on linux and it is working as expected. I can consume&produce with a DNS A record other than broker hostname.
I can also consume&produce with java clients when I use client.dns.lookup property.

However, it fails for confluent-kafka-dotnet 1.4.3 librdkafka 1.4.2 on Windows.
Is there a known issue on SASL via SSPI on Windows?

When we use dnsaliasnode01 instead of node01 (which is the part of broker's principle) we get the following error:

[KAFKA_ERROR] Message:sasl_plaintext://dnsaliasnode01:9092/bootstrap: Failed to initialize SASL authentication: InitializeSecurityContext failed: Target unknown (0x80090303) (after 0ms in state AUTH_REQ), Error:sasl_plaintext://dnsaliasnode01:9092/bootstrap: Failed to initialize SASL authentication: InitializeSecurityContext failed: Target unknown (0x80090303) (after 0ms in state AUTH_REQ)

How to reproduce
================

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [X] Confluent.Kafka nuget version.
 - [X] Apache Kafka version.
 - [X] Client configuration.
 - [X] Operating system.
 - [X] Provide logs (with "debug" : "..." as necessary in configuration).
 - [  ] Provide broker log excerpts.
 - [X] Critical issue.

**Comment by edenhill** [comment] 2020-06-10 09:22
The broker hostname (prior to resolve), as set by bootstrap.servers or through the broker's advertisted.listeners, is passed to the SSPI security context as part of the principal:
`<sasl.kerberos.service.name>/<hostname>`

https://github.com/edenhill/librdkafka/blob/master/src/rdkafka_sasl_win32.c#L509

Are you specifying the exact same bootstrap.servers for kafkacat as you are your windows application? If so then there is something going on in SSPI.
Do note that with SSPI we are using the currently logged on user's credentail to authenticate.

cc @rnpridgeon

**Comment by sysThematic** [comment] 2020-06-10 09:54
We don't have any kafka broker configuration for second dns record (dnsaliasnode01) 
both listeners and advertised listeners shows node name.
listeners=SASL_PLAINTEXT://node01.finansbank.com.tr:9092
advertised.listeners=SASL_PLAINTEXT://node01.finansbank.com.tr:9092

We are using the same value for bootstrap.servers on windows and for -b parameter for kafkacat.
If we use hostname of the broker on windows client it is working, and we have ACLs for logged on user of windows client, so I don't think we have problem there.

cc @serdarsert

**Comment by edenhill** [comment] 2020-06-10 09:59
The host resolution should work the same in librdkafka for both Linux and Windows, the mapping of CNAME to principal that client.dns.lookup=resolve_canonical_bootstrap_servers_only allows in the Java client is not supported in librdkafka, so if your Kerberos auth requires the hostname portion of the principal to match the secondary DNS entry then you are out of luck.

**Comment by sysThematic** [comment] 2020-06-10 10:04
We don't have any kafka broker configuration for second dns record (dnsaliasnode01)
both listeners and advertised listeners shows node name.
listeners=SASL_PLAINTEXT://node01.domain..com:9092
advertised.listeners=SASL_PLAINTEXT://node01.domain.com.:9092

We are using the same value for bootstrap.servers on windows and for -b parameter for kafkacat.
If we use hostname of the broker on windows client it is working, and we have ACLs for logged on user of windows client, so I don't think we have problem there.

cc @serdarsert

Note:deleted previous comment and make some editing.

**Comment by edenhill** [comment] 2020-06-10 10:13
If you can connect on Linux, but not on Windows, with `bootstrap.servers=dnsaliasnode01`, my guess is that Windows SSPI cares about the hostname part of the principal while Linux KRB5 does not.

Maybe there's something that needs to be done with SETSPN.

**Comment by rnpridgeon** [comment] 2020-06-10 11:23
The krb5 client libraries are performing this translation for librdkafka. It's actually configurable in the linux host's krb5.conf.

see dns_canonicalize_hostname
https://web.mit.edu/kerberos/krb5-devel/doc/admin/conf_files/krb5_conf.html#libdefaults

and service principal canonicalization
https://web.mit.edu/kerberos/krb5-devel/doc/admin/princ_dns.html#service-principal-canonicalization

Java ships with its own kerberos client implementation which is why you configure it with the application directly. 

I believe you can control this on a windows machine by setting the FEATURE_USE_CNAME_FOR_SPN_KB911149 register to True.

**Comment by anchitj** [comment] 2024-06-04 12:40
Closing as the issue is resolved.

**Closed by anchitj** 2024-06-04 12:40 UTC
