### ISSUE TITLE
1.9.0-RC7: High CPU Utilization with Producer

### ISSUE THREAD

**Issue by ryanliang** [confluentinc/confluent-kafka-dotnet#1809] opened 2022-05-06 16:36 UTC
Description
===========
When producing messages with `Produce` function, we are seeing high CPU utilization for librdkafka thread under Process Explorer(screenshots attached below).  This is only first seen with version v1.9.0.  Compared to v1.8.2, the CPU utilization for this thread is **increased from <0.01% to around 12%.**

How to reproduce
================
<details>
  <summary>docker-compose.yml</summary>
  
  ```yml
    ---
version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  ```
</details>

<details>
  <summary>program.cs</summary>
  
  ```cs
using System;
using Confluent.Kafka;

namespace KafkaNetDemo
{
    public class Program
    {
        public static void Main(string[] args)
        {
            var producerConfig = new ProducerConfig
            {
                BootstrapServers = "localhost:9092",
            };

            using var producer = new ProducerBuilder<string, string>(producerConfig).Build();

            Console.WriteLine("Press c and enter to replicate the issue and q to exit");
            
            while (Console.ReadKey().KeyChar != 'q')
            {
                for (var i = 0; i < 5; i++)
                {
                    var value = $"test_{i}_{DateTime.Now}";

                    try
                    {
                        producer.Produce("test", new Message<string, string> { Key = "key", Value = value });
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine(e);
                    }
                }
            }
        }
    }
}
  ```
</details>
v1.9.0-RC7 (CPU Utilization around 12%)

![github_v190rc7_cpu](https://user-images.githubusercontent.com/823147/167174176-4494f88c-2fd1-44f0-8918-82b56a8283c6.png)

v1.8.2 (CPU Utilization <0.01%)
![github_v182_cpu](https://user-images.githubusercontent.com/823147/167174185-ac8c89e0-9907-423e-b506-89660524f617.png)

Checklist
=========

Please provide the following information:
 - [x] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [x] Confluent.Kafka nuget version. 1.9.0-RC7
 - [x] Apache Kafka version. confluentinc/cp-kafka:7.0.0
 - [ ] Client configuration.
 - [x] Operating system. Windows 10 21H2, Windows Server 2016 Standard
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [x] Critical issue.

**Comment by mhowlett** [comment] 2022-05-18 13:08
that's not good.

cc: @edenhill

**Comment by mhowlett** [comment] 2022-05-18 13:19
oh, it's probably this: https://github.com/confluentinc/confluent-kafka-dotnet/pull/1774

**Comment by mhowlett** [comment] 2022-05-24 21:57
I was able to reproduce on Windows Server 2019 using your test app, and various variations of it.

I don't see the issue in v1.8.2, but if I update the librdkafka reference in 1.8.2 to 1.9.0-RC10, the issue does reproduce, implying the problem is in librdkafka.

The issue doesn't reproduce if the produce method is never called.

It also doesn't reproduce if the produce method is called only once.

However, CPU immediately shoots to 25% and stays there on my machine after the second produce call.

**Comment by ryanliang** [comment] 2022-05-24 22:09
@mhowlett , thanks for looking into this issue.  This is the same behavior as in my replication steps above.  I also didn't see CPU issue with v1.8.2.  This issue only happened in v1.9.0-RC*

**Comment by mhowlett** [comment] 2022-05-24 22:42
we're looking into it

**Comment by mhowlett** [comment] 2022-05-26 17:44
this PR is the cause: https://github.com/edenhill/librdkafka/commit/c9f9249bc80d59a430ba370b5f497995e2e855db

(looking into it)

**Comment by edenhill** [comment] 2022-05-31 16:01
Not sure I'm doing this correctly in WinDbg, but the address the profiler marks as a hot spot in v1.9.0-RC7 is the generic thread main loop trampoline:
```
0:000> ln librdkafka!rd_kafka_error_txn_requires_abort+0x7a70
Browse module
Set bu breakpoint

 [C:\projects\librdkafka\src\tinycthread.c @ 562] (00000001`801031b0)   librdkafka!_thrd_wrapper_function   |  (00000001`80103200)   librdkafka!_tinycthread_tss_cleanup
Exact matches:
    librdkafka!_thrd_wrapper_function (void *)

```

Which doesn't tell us much

**Comment by mhowlett** [comment] 2022-08-18 00:59
i believe this was resolved by the above PR.

**Closed by mhowlett** 2022-08-18 00:59 UTC
Labels: bug, librdkafka
